# **US-01**

In [3]:
import pandas as pd
from sqlalchemy import create_engine, text

engine = create_engine("mysql+pymysql://root:root@mariadb:3306")     # écriture (bronze, dq)
reader = create_engine("mysql+pymysql://reader:reader@mariadb:3306")  # lecture seule des sources

def lire(sql, eng=engine, **params):
    return pd.read_sql(text(sql), eng, params=params)

lire("SELECT COUNT(*) AS n FROM crm.client")

        n
0  100000

In [4]:
# Tables et nombre de colonnes
cols = lire("""
    SELECT table_schema AS base, table_name AS `table`, COUNT(*) AS colonnes
    FROM information_schema.columns
    WHERE table_schema IN ('cif','crm')
    GROUP BY table_schema, table_name""")

# Clé primaire
cles = lire("""
    SELECT table_schema AS base, table_name AS `table`,
           GROUP_CONCAT(column_name ORDER BY ordinal_position) AS cle_primaire
    FROM information_schema.key_column_usage
    WHERE table_schema IN ('cif','crm') AND constraint_name = 'PRIMARY'
    GROUP BY table_schema, table_name""")

inventaire = cols.merge(cles, how="left", on=["base", "table"])

# Comptage exact (table_rows n'est qu'une estimation)
inventaire["lignes"] = [int(lire(f"SELECT COUNT(*) AS n FROM {b}.{t}").n[0])
                        for b, t in zip(inventaire.base, inventaire.table)]

inventaire = inventaire.sort_values(["base", "table"], ascending=[False, True]).reset_index(drop=True)
inventaire

  base         table  colonnes cle_primaire  lignes
0  crm        client        13    client_id  100000
1  crm       contrat         9   contrat_id  100000
2  crm      sinistre        10  sinistre_id  100000
3  crm  type_contrat         3    code_type      12
4  cif       clients        10      column0   40000
5  cif        compte         4      column0   45000
6  cif          pays         2    code_pays     250

In [7]:
sans_pk = inventaire[inventaire.cle_primaire.isna()][["base", "table"]]
print(f"{len(sans_pk)} table(s) sans clé primaire")
sans_pk

0 table(s) sans clé primaire

Empty DataFrame
Columns: [base, table]
Index: []

In [8]:
nuls = []
for b, t in zip(inventaire.base, inventaire.table):
    df = lire(f"SELECT * FROM {b}.{t}")
    n = df.isna().sum()
    nuls.append({
        "base": b, "table": t,
        "total_nuls": int(n.sum()),
        "colonnes_avec_nuls": int((n > 0).sum()),
        "colonne_max_nuls": n.idxmax() if n.max() > 0 else "-",
        "nb_nuls_max": int(n.max()),
    })
nuls = pd.DataFrame(nuls)
nuls

,base,table,total_nuls,colonnes_avec_nuls,colonne_max_nuls,nb_nuls_max
0,crm,client,133918,6,raison_sociale,95723
1,crm,contrat,7460,1,date_derniere_cotisation,7460
2,crm,sinistre,0,0,-,0
3,crm,type_contrat,0,0,-,0
4,cif,clients,26486,4,column9,18872
5,cif,compte,0,0,-,0
6,cif,pays,0,0,-,0

In [9]:
doublons = []
for b, t, pk in zip(inventaire.base, inventaire.table, inventaire.cle_primaire):
    cle = f"CONCAT_WS('|', {pk})"
    d = lire(f"SELECT COUNT(*) - COUNT(DISTINCT {cle}) AS n FROM {b}.{t}").n[0]
    doublons.append({"base": b, "table": t, "doublons_cle": int(d)})
doublons = pd.DataFrame(doublons)
doublons

  base         table  doublons_cle
0  crm        client             0
1  crm       contrat             0
2  crm      sinistre             0
3  crm  type_contrat             0
4  cif       clients             0
5  cif        compte             0
6  cif          pays             0

In [10]:
def val(sql):
    """Renvoie la première ligne d'une requête sous forme de dictionnaire."""
    return lire(sql).iloc[0].to_dict()

c   = val("SELECT SUM(raison_sociale IS NOT NULL) AS pm FROM crm.client")
ct  = val("SELECT SUM(assure_id = '0') AS sentinelle FROM crm.contrat")
s   = val("SELECT COUNT(DISTINCT canal_saisie) AS canaux, COUNT(DISTINCT contrat_id) AS contrats FROM crm.sinistre")
tc  = val("SELECT COUNT(*) AS types, COUNT(DISTINCT branche) AS branches FROM crm.type_contrat")
cpt = val("SELECT COUNT(*) AS comptes, COUNT(DISTINCT column1) AS ids FROM cif.compte")
p   = val("SELECT COUNT(*) AS pays FROM cif.pays")

particularites = pd.DataFrame([
    {"base": "crm", "table": "client",
     "particularite": f"{int(c['pm'])} personnes morales (raison_sociale renseignée, nom vide)"},
    {"base": "crm", "table": "contrat",
     "particularite": f"{int(ct['sentinelle'])} contrats avec assure_id = '0' (valeur sentinelle)"},
    {"base": "crm", "table": "sinistre",
     "particularite": f"{int(s['canaux'])} canaux de saisie, {int(s['contrats'])} contrats distincts concernés"},
    {"base": "crm", "table": "type_contrat",
     "particularite": f"{int(tc['types'])} types répartis sur {int(tc['branches'])} branches"},
    {"base": "cif", "table": "clients",
     "particularite": "10 colonnes aux noms anonymes (column0 à column9), sans documentation"},
    {"base": "cif", "table": "compte",
     "particularite": f"{int(cpt['comptes'])} comptes pour {int(cpt['ids'])} identifiants CIF distincts"},
    {"base": "cif", "table": "pays",
     "particularite": f"{int(p['pays'])} pays dans le référentiel"},
])
particularites

  base         table                                      particularite
0  crm        client  4277 personnes morales (raison_sociale renseig...
1  crm       contrat  40000 contrats avec assure_id = '0' (valeur se...
2  crm      sinistre  4 canaux de saisie, 62782 contrats distincts c...
3  crm  type_contrat                   12 types répartis sur 3 branches
4  cif       clients  10 colonnes aux noms anonymes (column0 à colum...
5  cif        compte  45000 comptes pour 40000 identifiants CIF dist...
6  cif          pays                       250 pays dans le référentiel

Cellule 7: La table inventaire finale

In [12]:
us01 = (inventaire
        .merge(nuls, on=["base", "table"])
        .merge(doublons, on=["base", "table"])
        .merge(particularites, on=["base", "table"]))

def observation(r):
    txt = f"{r.doublons_cle} doublon de clé"
    if r.total_nuls:
        txt += f" ; {r.total_nuls} nuls sur {r.colonnes_avec_nuls} colonne(s), max sur {r.colonne_max_nuls} ({r.nb_nuls_max})"
    else:
        txt += " ; aucun nul"
    return txt + f" ; {r.particularite}"

us01["Observation chiffrée"] = us01.apply(observation, axis=1)

livrable_us01 = us01.rename(columns={"base": "Source", "table": "Table",
                                     "lignes": "Lignes", "cle_primaire": "Clé primaire"})[
    ["Source", "Table", "Lignes", "Clé primaire", "Observation chiffrée"]]

pd.set_option("display.max_colwidth", None)
livrable_us01

,Source,Table,Lignes,Clé primaire,Observation chiffrée
0,crm,client,100000,client_id,"0 doublon de clé ; 133918 nuls sur 6 colonne(s), max sur raison_sociale (95723) ; 4277 personnes morales (raison_sociale renseignée, nom vide)"
1,crm,contrat,100000,contrat_id,"0 doublon de clé ; 7460 nuls sur 1 colonne(s), max sur date_derniere_cotisation (7460) ; 40000 contrats avec assure_id = '0' (valeur sentinelle)"
2,crm,sinistre,100000,sinistre_id,"0 doublon de clé ; aucun nul ; 4 canaux de saisie, 62782 contrats distincts concernés"
3,crm,type_contrat,12,code_type,0 doublon de clé ; aucun nul ; 12 types répartis sur 3 branches
4,cif,clients,40000,column0,"0 doublon de clé ; 26486 nuls sur 4 colonne(s), max sur column9 (18872) ; 10 colonnes aux noms anonymes (column0 à column9), sans documentation"
5,cif,compte,45000,column0,0 doublon de clé ; aucun nul ; 45000 comptes pour 40000 identifiants CIF distincts
6,cif,pays,250,code_pays,0 doublon de clé ; aucun nul ; 250 pays dans le référentiel

# **US-02**

Connexions et paramètres

In [13]:
import pandas as pd
from sqlalchemy import create_engine, text

reader = create_engine("mysql+pymysql://reader:reader@mariadb:3306")  # lecture seule sur cif et crm
engine = create_engine("mysql+pymysql://root:root@mariadb:3306")      # écriture dans bronze et dq

BATCH = "L-2026-10-01"   # identifiant du lot

def lire(sql, eng=engine, **params):
    return pd.read_sql(text(sql), eng, params=params)

def executer(sql, **params):
    with engine.begin() as c:
        c.execute(text(sql), params)

SOURCES = [("crm", "client",       "crm_client"),
           ("crm", "contrat",      "crm_contrat"),
           ("crm", "type_contrat", "crm_type_contrat"),
           ("crm", "sinistre",     "crm_sinistre"),
           ("cif", "clients",      "cif_clients"),
           ("cif", "compte",       "cif_compte"),
           ("cif", "pays",         "cif_pays")]

Vérifier que le compte reader est bien en lecture seule

In [14]:
# 1. Ses droits
display(lire("SHOW GRANTS FOR 'reader'@'%'"))

# 2. Il peut lire
print("Lecture OK :", lire("SELECT COUNT(*) AS n FROM crm.client", reader).n[0], "lignes")

# 3. Il ne peut pas écrire (WHERE 1=0 : ne toucherait aucune ligne, même si c'était autorisé)
try:
    with reader.begin() as c:
        c.execute(text("DELETE FROM crm.type_contrat WHERE 1=0"))
    print("❌ PROBLÈME : reader a pu écrire")
except Exception as e:
    print("✅ Écriture refusée pour reader :", str(e.orig)[:80])

                                                                                     Grants for reader@%
0  GRANT USAGE ON *.* TO `reader`@`%` IDENTIFIED BY PASSWORD '*FC69E042CE30D92E2952335F690CF2345C812E36'
1                                                                GRANT SELECT ON `cif`.* TO `reader`@`%`
2                                                                GRANT SELECT ON `crm`.* TO `reader`@`%`

Lecture OK : 100000 lignes
✅ Écriture refusée pour reader : (1142, "DELETE command denied to user 'reader'@'172.18.0.3' for table `crm`.`typ

La fonction d’ingestion

In [15]:
def ingerer(base, table, cible):
    # 1. Lire la source avec le compte lecture seule.
    #    coerce_float=False : 184.10 reste 184.10 (sinon il devient 184.1 et la porte B échoue)
    #    .astype("string") : tout en texte, bronze ne transforme rien
    df = pd.read_sql(text(f"SELECT * FROM {base}.{table}"), reader,
                     coerce_float=False).astype("string")
    df = df.astype(object).where(df.notna(), None)          # les NULL restent NULL

    # 2. Empreinte de chaque ligne, calculée AVANT d'ajouter les métadonnées
    h = pd.util.hash_pandas_object(df.fillna("\\N").astype(str), index=False)
    df["_row_hash"] = [f"{v:016x}" for v in h]              # 16 caractères hexadécimaux

    # 3. Métadonnées (_ingested_at est rempli par MariaDB)
    df["_batch_id"] = BATCH
    df["_source_system"] = base

    # 4. Idempotence : on supprime d'abord ce lot, puis on le réinsère
    #    → relancer donne le même résultat, sans doublon
    with engine.begin() as c:
        c.execute(text(f"DELETE FROM bronze.{cible} WHERE _batch_id = :b"), {"b": BATCH})
        df.to_sql(cible, c, schema="bronze", if_exists="append",
                  index=False, chunksize=10_000)
    return len(df)

Lancer l’ingestion des 7 tables

In [16]:
# Déclarer le lot comme « en cours »
executer("""INSERT INTO dq.lot_ingestion (batch_id, statut) VALUES (:b, 'EN_COURS')
            ON DUPLICATE KEY UPDATE statut = 'EN_COURS', finished_at = NULL""", b=BATCH)

for base, table, cible in SOURCES:
    n = ingerer(base, table, cible)
    print(f"{base}.{table:<13} → bronze.{cible:<17} {n:>7} lignes")

# Clore le lot
executer("UPDATE dq.lot_ingestion SET statut = 'TERMINE', finished_at = NOW() WHERE batch_id = :b", b=BATCH)

crm.client        → bronze.crm_client         100000 lignes
crm.contrat       → bronze.crm_contrat        100000 lignes
crm.type_contrat  → bronze.crm_type_contrat       12 lignes
crm.sinistre      → bronze.crm_sinistre       100000 lignes
cif.clients       → bronze.cif_clients         40000 lignes
cif.compte        → bronze.cif_compte          45000 lignes
cif.pays          → bronze.cif_pays              250 lignes

Cellule 5: Vérification : une ligne bronze par ligne source + les 4 métadonnées remplies (RQ-022)

In [17]:
controle = []
for base, table, cible in SOURCES:
    r = lire(f"""
        SELECT COUNT(*) AS bronze,
               SUM(_batch_id IS NULL OR _source_system IS NULL
                   OR _ingested_at IS NULL OR _row_hash IS NULL) AS metadonnee_manquante
        FROM bronze.{cible} WHERE _batch_id = '{BATCH}'""").iloc[0]
    src = lire(f"SELECT COUNT(*) AS n FROM {base}.{table}", reader).n[0]
    controle.append({"table": cible, "source": int(src), "bronze": int(r.bronze),
                     "ecart": int(r.bronze - src),
                     "metadonnee_manquante": int(r.metadonnee_manquante or 0)})
controle = pd.DataFrame(controle)
controle

              table  source  bronze  ecart  metadonnee_manquante
0        crm_client  100000  100000      0                     0
1       crm_contrat  100000  100000      0                     0
2  crm_type_contrat      12      12      0                     0
3      crm_sinistre  100000  100000      0                     0
4       cif_clients   40000   40000      0                     0
5        cif_compte   45000   45000      0                     0
6          cif_pays     250     250      0                     0

relancer le même lot ne crée aucun doublon

In [18]:
avant = lire("SELECT COUNT(*) AS n FROM bronze.crm_client").n[0]
ingerer("crm", "client", "crm_client")          # on relance le même lot
apres = lire("SELECT COUNT(*) AS n FROM bronze.crm_client").n[0]
print(f"Avant relance : {avant} · après relance : {apres} · doublons créés : {apres - avant}")

Avant relance : 100000 · après relance : 100000 · doublons créés : 0

Visualisation de la table bronze.crm_client

In [19]:
lire("SELECT client_id, nom, cp, pays, _batch_id, _source_system, _ingested_at, _row_hash "
     "FROM bronze.crm_client LIMIT 5")

,client_id,nom,cp,pays,_batch_id,_source_system,_ingested_at,_row_hash
0,A-1000,Thomas,69300,FR,L-2026-10-01,crm,2026-10-21 11:38:58,8fe9e59d3f5268ea
1,A-10000,Leroy,73000,FR,L-2026-10-01,crm,2026-10-21 11:38:58,bf96f99ffb10ed08
2,A-10001,Dumas,71000,,L-2026-10-01,crm,2026-10-21 11:38:58,5471aff6d3a407b8
3,A-10002,Denis,69009,FR,L-2026-10-01,crm,2026-10-21 11:38:58,4ac5023b52ef397a
4,A-10003,Perrin,69100,FR,L-2026-10-01,crm,2026-10-21 11:38:58,e33662a2cdbedbb2

# **US-03**

In [20]:
import pandas as pd
from sqlalchemy import create_engine, text

reader = create_engine("mysql+pymysql://reader:reader@mariadb:3306")  # lecture seule sur cif et crm
engine = create_engine("mysql+pymysql://root:root@mariadb:3306")      # écriture dans bronze et dq

BATCH = "L-2026-10-01"   # identifiant du lot

def lire(sql, eng=engine):
    return pd.read_sql(text(sql), eng)

def executer(sql, **params):
    with engine.begin() as c:
        c.execute(text(sql), params)

SOURCES = [("crm", "client",       "crm_client"),
           ("crm", "contrat",      "crm_contrat"),
           ("crm", "type_contrat", "crm_type_contrat"),
           ("crm", "sinistre",     "crm_sinistre"),
           ("cif", "clients",      "cif_clients"),
           ("cif", "compte",       "cif_compte"),
           ("cif", "pays",         "cif_pays")]

### Fonctions

In [22]:
# lire() avec paramètres nommés (compatible avec les anciens appels lire(sql, reader))
def lire(sql, eng=engine, **params):
    return pd.read_sql(text(sql), eng, params=params)

def colonnes_table(base, table, avec_meta=False):
    """Colonnes d'une table dans l'ordre. Par défaut : colonnes métier seulement (sans _meta ni bronze_row_id)."""
    cols = lire("""SELECT column_name FROM information_schema.columns
                   WHERE table_schema = :s AND table_name = :t
                   ORDER BY ordinal_position""", s=base, t=table).column_name.tolist()
    cols = [c for c in cols if c != "bronze_row_id"]
    return cols if avec_meta else [c for c in cols if not c.startswith("_")]

def somme_controle(base, table, colonnes, ou="", eng=engine):
    """(nombre de lignes, SUM des CRC32 de chaque ligne) sur les colonnes données."""
    liste = ", ".join(f"`{c}`" for c in colonnes)
    r = lire(f"""SELECT COUNT(*) AS n,
                        COALESCE(SUM(CRC32(CONCAT_WS('|', {liste}))), 0) AS crc
                 FROM {base}.{table} {ou}""", eng)
    return int(r.n[0]), int(r.crc[0])

def ecart_rq021(base, table, cible, ou_bronze=None):
    """Réconcilie une table source avec sa copie bronze. Renvoie (n_source, n_bronze, ecarts)."""
    if ou_bronze is None:
        ou_bronze = f"WHERE _batch_id = '{BATCH}'"
    cols = colonnes_table(base, table)                      # colonnes lues dans la SOURCE
    n_s, crc_s = somme_controle(base, table, cols, eng=reader)
    n_b, crc_b = somme_controle("bronze", cible, cols, ou_bronze)
    return n_s, n_b, abs(n_s - n_b) + int(crc_s != crc_b)

def mesurer(couche, regle, table, nb_testees, nb_echecs):
    """Écrit une mesure dans dq.dq_history (taux_conformite est calculé par MariaDB) et renvoie la ligne."""
    nb_testees, nb_echecs = int(nb_testees), int(nb_echecs)

    # Idempotence : relancer la porte sur le même lot ne crée pas de doublon
    executer("""DELETE FROM dq.dq_history
                WHERE batch_id = :b AND couche = :c AND rule_id = :r AND table_cible = :t""",
             b=BATCH, c=couche, r=regle, t=table)
    executer("""INSERT INTO dq.dq_history
                    (batch_id, couche, rule_id, table_cible, nb_testees, nb_echecs, mesure_le)
                VALUES (:b, :c, :r, :t, :n, :e, NOW())""",
             b=BATCH, c=couche, r=regle, t=table, n=nb_testees, e=nb_echecs)

    # On relit le taux calculé par la base, pour afficher la vraie valeur
    taux = lire("""SELECT taux_conformite FROM dq.dq_history
                   WHERE batch_id = :b AND couche = :c AND rule_id = :r AND table_cible = :t""",
                b=BATCH, c=couche, r=regle, t=table).taux_conformite[0]

    return {"batch_id": BATCH, "couche": couche, "rule_id": regle, "table": table,
            "nb_testees": nb_testees, "nb_echecs": nb_echecs, "taux_conformite": float(taux)}

 Cellule 3: Porte B sur les 7 tables (RQ-021 et RQ-022)

In [23]:
porte_b, bilan = [], []
for base, table, cible in SOURCES:
    # RQ-021 : comptage + somme de contrôle
    n_src, n_brz, ecarts = ecart_rq021(base, table, cible)
    porte_b.append(mesurer("BRONZE", "RQ-021", cible, n_src, ecarts))
    bilan.append({"regle": "RQ-021", "table": cible, "source": n_src, "bronze": n_brz, "ecarts": ecarts})

    # RQ-022 : chaque ligne porte lot, source, horodatage et empreinte
    meta = lire(f"""SELECT COUNT(*) AS n,
                           COALESCE(SUM(_batch_id IS NULL OR _batch_id = '' OR _source_system IS NULL OR _source_system = ''
                                        OR _ingested_at IS NULL OR _row_hash IS NULL OR _row_hash = ''), 0) AS ko
                    FROM bronze.{cible} WHERE _batch_id = '{BATCH}'""")
    porte_b.append(mesurer("BRONZE", "RQ-022", cible, int(meta.n[0]), int(meta.ko[0])))
    bilan.append({"regle": "RQ-022", "table": cible, "source": None, "bronze": int(meta.n[0]), "ecarts": int(meta.ko[0])})

print(pd.DataFrame(porte_b).sort_values(["rule_id", "table"]).to_string(index=False))  # aucun écart attendu
bilan = pd.DataFrame(bilan).sort_values(["regle", "table"])
display(bilan)
print("PORTE B :", "OUVERTE ✅" if (bilan.ecarts == 0).all() else "FERMÉE ❌")

    batch_id couche rule_id            table  nb_testees  nb_echecs  taux_conformite
L-2026-10-01 BRONZE  RQ-021      cif_clients       40000          0            100.0
L-2026-10-01 BRONZE  RQ-021       cif_compte       45000          0            100.0
L-2026-10-01 BRONZE  RQ-021         cif_pays         250          0            100.0
L-2026-10-01 BRONZE  RQ-021       crm_client      100000          0            100.0
L-2026-10-01 BRONZE  RQ-021      crm_contrat      100000          0            100.0
L-2026-10-01 BRONZE  RQ-021     crm_sinistre      100000          0            100.0
L-2026-10-01 BRONZE  RQ-021 crm_type_contrat          12          0            100.0
L-2026-10-01 BRONZE  RQ-022      cif_clients       40000          0            100.0
L-2026-10-01 BRONZE  RQ-022       cif_compte       45000          0            100.0
L-2026-10-01 BRONZE  RQ-022         cif_pays         250          0            100.0
L-2026-10-01 BRONZE  RQ-022       crm_client      100000          0            100.0
L-2026-10-01 BRONZE  RQ-022      crm_contrat      100000          0            100.0
L-2026-10-01 BRONZE  RQ-022     crm_sinistre      100000          0            100.0
L-2026-10-01 BRONZE  RQ-022 crm_type_contrat          12          0            100.0

     regle             table    source  bronze  ecarts
8   RQ-021       cif_clients   40000.0   40000       0
10  RQ-021        cif_compte   45000.0   45000       0
12  RQ-021          cif_pays     250.0     250       0
0   RQ-021        crm_client  100000.0  100000       0
2   RQ-021       crm_contrat  100000.0  100000       0
6   RQ-021      crm_sinistre  100000.0  100000       0
4   RQ-021  crm_type_contrat      12.0      12       0
9   RQ-022       cif_clients       NaN   40000       0
11  RQ-022        cif_compte       NaN   45000       0
13  RQ-022          cif_pays       NaN     250       0
1   RQ-022        crm_client       NaN  100000       0
3   RQ-022       crm_contrat       NaN  100000       0
7   RQ-022      crm_sinistre       NaN  100000       0
5   RQ-022  crm_type_contrat       NaN      12       0

PORTE B : OUVERTE ✅

### vérifier l'écriture dans dq_history

In [24]:
# Attendu : 14 lignes (7 tables × 2 règles), couche BRONZE, nb_echecs = 0, taux_conformite = 100
display(lire("""SELECT id, batch_id, couche, rule_id, table_cible, nb_testees, nb_echecs, taux_conformite, mesure_le
                FROM dq.dq_history
                WHERE batch_id = :b AND couche = 'BRONZE'
                ORDER BY rule_id, table_cible""", b=BATCH))

,id,batch_id,couche,rule_id,table_cible,nb_testees,nb_echecs,taux_conformite,mesure_le
0,9,L-2026-10-01,BRONZE,RQ-021,cif_clients,40000,0,100.0,2026-10-21 11:39:52
1,11,L-2026-10-01,BRONZE,RQ-021,cif_compte,45000,0,100.0,2026-10-21 11:39:53
2,13,L-2026-10-01,BRONZE,RQ-021,cif_pays,250,0,100.0,2026-10-21 11:39:53
3,1,L-2026-10-01,BRONZE,RQ-021,crm_client,100000,0,100.0,2026-10-21 11:39:50
4,3,L-2026-10-01,BRONZE,RQ-021,crm_contrat,100000,0,100.0,2026-10-21 11:39:51
5,7,L-2026-10-01,BRONZE,RQ-021,crm_sinistre,100000,0,100.0,2026-10-21 11:39:52
6,5,L-2026-10-01,BRONZE,RQ-021,crm_type_contrat,12,0,100.0,2026-10-21 11:39:51
7,10,L-2026-10-01,BRONZE,RQ-022,cif_clients,40000,0,100.0,2026-10-21 11:39:52
8,12,L-2026-10-01,BRONZE,RQ-022,cif_compte,45000,0,100.0,2026-10-21 11:39:53
9,14,L-2026-10-01,BRONZE,RQ-022,cif_pays,250,0,100.0,2026-10-21 11:39:53
10,2,L-2026-10-01,BRONZE,RQ-022,crm_client,100000,0,100.0,2026-10-21 11:39:50
11,4,L-2026-10-01,BRONZE,RQ-022,crm_contrat,100000,0,100.0,2026-10-21 11:39:51
12,8,L-2026-10-01,BRONZE,RQ-022,crm_sinistre,100000,0,100.0,2026-10-21 11:39:52
13,6,L-2026-10-01,BRONZE,RQ-022,crm_type_contrat,12,0,100.0,2026-10-21 11:39:51

### outils de l'épreuve de l'écart volontaire

In [25]:
def copie_test(cible):
    """Crée bronze.<cible>_test, copie du lot courant. Ne touche jamais à bronze elle-même."""
    t = f"{cible}_test"
    executer(f"DROP TABLE IF EXISTS bronze.{t}")
    executer(f"CREATE TABLE bronze.{t} LIKE bronze.{cible}")
    executer(f"INSERT INTO bronze.{t} SELECT * FROM bronze.{cible} WHERE _batch_id = '{BATCH}'")
    return t

def alt_modification(t, cols):      # change une valeur (fonctionne même si elle était NULL)
    c = f"`{cols[0]}`"
    executer(f"UPDATE bronze.{t} SET {c} = CONCAT(COALESCE({c}, ''), '#') LIMIT 1")

def alt_suppression(t, cols):       # supprime une ligne
    executer(f"DELETE FROM bronze.{t} LIMIT 1")

def alt_doublon(t, cols):           # insère un doublon (sans bronze_row_id)
    liste = ", ".join(f"`{c}`" for c in colonnes_table("bronze", t, avec_meta=True))
    executer(f"INSERT INTO bronze.{t} ({liste}) SELECT {liste} FROM bronze.{t} LIMIT 1")

SCENARIOS = {"modification": alt_modification,
             "suppression":  alt_suppression,
             "doublon":      alt_doublon}

### Cellule 6: épreuve sur les 7 tables × 3 altérations

In [26]:
epreuve = []
for base, table, cible in SOURCES:
    cols = colonnes_table(base, table)
    for nom, alterer in SCENARIOS.items():
        t = f"{cible}_test"
        try:
            copie_test(cible)
            _, _, avant = ecart_rq021(base, table, t, ou_bronze="")   # témoin : doit valoir 0
            alterer(t, cols)
            _, _, apres = ecart_rq021(base, table, t, ou_bronze="")   # doit être > 0
            epreuve.append({"table": cible, "alteration": nom, "ecarts_avant": avant,
                            "ecarts_apres": apres,
                            "porte": "FERMÉE ✅" if (avant == 0 and apres > 0) else "ANOMALIE ❌"})
        except Exception as e:
            epreuve.append({"table": cible, "alteration": nom, "ecarts_avant": None,
                            "ecarts_apres": None, "porte": f"ERREUR : {str(e)[:70]}"})
        finally:
            executer(f"DROP TABLE IF EXISTS bronze.{t}")              # dans tous les cas

epreuve = pd.DataFrame(epreuve)
display(epreuve)

restes = [x for x in lire("SELECT table_name AS t FROM information_schema.tables WHERE table_schema = 'bronze'").t if x.endswith("_test")]
print("Tables _test restantes :", restes or "aucune ✅")

               table    alteration  ecarts_avant  ecarts_apres     porte
0         crm_client  modification             0             1  FERMÉE ✅
1         crm_client   suppression             0             2  FERMÉE ✅
2         crm_client       doublon             0             2  FERMÉE ✅
3        crm_contrat  modification             0             1  FERMÉE ✅
4        crm_contrat   suppression             0             2  FERMÉE ✅
5        crm_contrat       doublon             0             2  FERMÉE ✅
6   crm_type_contrat  modification             0             1  FERMÉE ✅
7   crm_type_contrat   suppression             0             2  FERMÉE ✅
8   crm_type_contrat       doublon             0             2  FERMÉE ✅
9       crm_sinistre  modification             0             1  FERMÉE ✅
10      crm_sinistre   suppression             0             2  FERMÉE ✅
11      crm_sinistre       doublon             0             2  FERMÉE ✅
12       cif_clients  modification             0             1  FERMÉE ✅
13       cif_clients   suppression             0             2  FERMÉE ✅
14       cif_clients       doublon             0             2  FERMÉE ✅
15        cif_compte  modification             0             1  FERMÉE ✅
16        cif_compte   suppression             0             2  FERMÉE ✅
17        cif_compte       doublon             0             2  FERMÉE ✅
18          cif_pays  modification             0             1  FERMÉE ✅
19          cif_pays   suppression             0             2  FERMÉE ✅
20          cif_pays       doublon             0             2  FERMÉE ✅

Tables _test restantes : aucune ✅

localiser un écart si la porte est fermée ( optionnelle si il y a le cas de la porte fermée )

In [28]:
def diagnostic(base, table, cible):
    """Compare le SUM(CRC32) colonne par colonne pour trouver celle qui diffère."""
    for c in colonnes_table(base, table):
        s = lire(f"SELECT COALESCE(SUM(CRC32(`{c}`)), 0) AS x FROM {base}.{table}", reader).x[0]
        b = lire(f"SELECT COALESCE(SUM(CRC32(`{c}`)), 0) AS x FROM bronze.{cible} WHERE _batch_id = '{BATCH}'").x[0]
        if int(s) != int(b):
            print(f"écart sur la colonne {c}: source={int(s)} bronze={int(b)}")

# diagnostic("crm", "contrat", "crm_contrat")

Cellule 8: épreuve conversion + porte B

In [29]:
# Épreuve conversion : combien de montants seraient abîmés sans la correction ?
sql = "SELECT contrat_id, prime_annuelle FROM crm.contrat"
sans_correction = pd.read_sql(text(sql), reader, coerce_float=True)   # lecture en nombres à virgule
avec_correction = pd.read_sql(text(sql), reader, coerce_float=False)  # lecture fidèle (US-02)

diff = sans_correction.prime_annuelle.astype(str) != avec_correction.prime_annuelle.astype(str)
print(f"{diff.sum()} montants sur {len(diff)} seraient modifiés sans coerce_float=False")
display(pd.DataFrame({
    "contrat_id": avec_correction.contrat_id[diff].head(),
    "source (fidèle)": avec_correction.prime_annuelle[diff].astype(str).head(),
    "sans correction": sans_correction.prime_annuelle[diff].astype(str).head()}))

9912 montants sur 100000 seraient modifiés sans coerce_float=False

    contrat_id source (fidèle) sans correction
19   CT0000020          184.10           184.1
35   CT0000036         1352.10          1352.1
61   CT0000062          326.60           326.6
68   CT0000069          119.60           119.6
114  CT0000115          342.60           342.6

# **US-06**

In [30]:
import pandas as pd
from sqlalchemy import create_engine, text

reader = create_engine("mysql+pymysql://reader:reader@mariadb:3306")  # lecture seule sur cif et crm
engine = create_engine("mysql+pymysql://root:root@mariadb:3306")      # écriture dans bronze et dq

BATCH = "L-2026-10-01"   # identifiant du lot

def lire(sql, eng=engine, **params):
    return pd.read_sql(text(sql), eng, params=params)

Cellule 1 : Générer le rapport HTML

In [31]:
# US-06 · Rapport YData-Profiling de crm.client
from ydata_profiling import ProfileReport
import os

df = lire("SELECT * FROM crm.client", reader)        # 100 000 lignes, telles que livrées par la source

DOSSIER_RAPPORTS = "/home/jovyan/work/reports" if os.path.isdir("/home/jovyan/work/reports") else "reports"
os.makedirs(DOSSIER_RAPPORTS, exist_ok=True)

profil = ProfileReport(df, title="AssurConnect — Profilage crm.client (100 000 lignes)", explorative=True)
profil.to_file(f"{DOSSIER_RAPPORTS}/ydata_profiling_client.html")
print("rapport écrit :", f"{DOSSIER_RAPPORTS}/ydata_profiling_client.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/13 [00:00<?, ?it/s]
  8%|▊         | 1/13 [00:08<01:41,  8.44s/it]
 15%|█▌        | 2/13 [00:08<00:39,  3.60s/it]
 69%|██████▉   | 9/13 [00:08<00:02,  1.86it/s]
100%|██████████| 13/13 [00:11<00:00,  1.13it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

rapport écrit : /home/jovyan/work/reports/ydata_profiling_client.html

Cellule 2 : Le tableau de santé de chaque colonne (sur bronze)

In [32]:
# On profile BRONZE (le lot courant), sans les métadonnées
b = lire("SELECT * FROM bronze.crm_client WHERE _batch_id = :b", b=BATCH)
b = b[[c for c in b.columns if not c.startswith("_") and c != "bronze_row_id"]]

stats = pd.DataFrame({
    "nuls":      b.isna().sum(),                                             # NULL
    "vides":     (b == "").sum(),                                            # chaîne vide ''
    "blancs":    ((b.apply(lambda s: s.str.strip()) == "") & (b != "")).sum(),  # que des espaces
    "distincts": b.nunique(),                                                # cardinalité
    "long_min":  b.apply(lambda s: s.str.len().min()).astype("Int64"),
    "long_max":  b.apply(lambda s: s.str.len().max()).astype("Int64"),
})
stats

                 nuls  vides  blancs  distincts  long_min  long_max
client_id           0      0       0     100000         6         7
type_personne       0      0       0          8         6        12
nom              4277      0       0        784         3         9
prenom           4277      0       0        293         2        10
raison_sociale  95723      0       0       3229        12        27
date_naissance   4277      0       0      28413        10        10
adresse             0      0       0       7561        10        31
cp                  0      0       0        230         4         8
ville               0      0       0        172         3        24
pays                0    400       0         18         0         6
telephone        5999   2000    2000      88702         0        17
email           19365      0       0      77795        13        36
date_creation       0      0       0       5391        10        10

Cellule 3 : Les vérifications ciblées

In [33]:
print("Clé client_id : lignes", len(b), "| distinctes", b.client_id.nunique(),
      "| nulles", int(b.client_id.isna().sum()))

print("\nDomaine de type_personne :")
display(b.type_personne.value_counts(dropna=False))

print("\nPays :", b.pays.nunique(), "valeurs distinctes")
display(b.pays.value_counts(dropna=False).head(12))

Clé client_id : lignes 100000 | distinctes 100000 | nulles 0

Domaine de type_personne :

type_personne
souscripteur    49898
assure          28944
prospect        20958
client             60
Souscripteur       50
assuré             40
SOUSCRIPTEUR       30
prosp.             20
Name: count, dtype: int64

Pays : 18 valeurs distinctes

pays
FR        95437
France     1200
F           600
Frnace      400
            400
fr          400
ES          243
IT          231
CH          227
DE          222
BE          216
LU          125
Name: count, dtype: int64

Cellule 4 : Manques normaux ou vrais défauts ?

In [34]:
# nom et raison_sociale se complètent : une entreprise n'a pas de nom, un particulier pas de raison sociale
print("ni nom ni raison :", int((b.nom.isna() & b.raison_sociale.isna()).sum()),
      "| les deux :", int((b.nom.notna() & b.raison_sociale.notna()).sum()),
      "| nom nul :", int(b.nom.isna().sum()),
      "| raison nulle :", int(b.raison_sociale.isna().sum()))

print("Naissance :", b.date_naissance.dropna().min(), "→", b.date_naissance.dropna().max(),
      "| création :", b.date_creation.dropna().min(), "→", b.date_creation.dropna().max())

# Le constat que le rapport NE signale PAS : le zéro initial perdu du code postal
print("CP à 4 chiffres (zéro initial perdu) :", int(b.cp.str.fullmatch(r"\d{4}").sum()))

ni nom ni raison : 0 | les deux : 0 | nom nul : 4277 | raison nulle : 95723
Naissance : 1938-04-11 → 2026-07-13 | création : 2008-09-11 → 2026-09-30
CP à 4 chiffres (zéro initial perdu) : 2068

Vérification rapide des clients nés aprés 2008

In [35]:
lire("""SELECT type_personne, COUNT(*) AS n
        FROM bronze.crm_client
        WHERE _batch_id = :b AND date_naissance > '2008-10-01'
        GROUP BY type_personne""", b=BATCH)

  type_personne      n
0  SOUSCRIPTEUR      3
1  Souscripteur      3
2        assure  10301
3        assuré      5
4        client      7
5        prosp.      4
6  souscripteur    156

# **US-07**

Cellule 1 : Les motifs des 3 colonnes

In [36]:
def motif(s):
    """9 remplace un chiffre, A une lettre : on voit la forme d'une valeur, pas la valeur."""
    return (s.fillna("<NULL>")
             .str.replace(r"[0-9]", "9", regex=True)
             .str.replace(r"[A-Za-z]", "A", regex=True))

for colonne in ["cp", "telephone", "pays"]:
    print(f"\nMotifs de {colonne} :")
    display(motif(b[colonne]).value_counts().head(12))

Motifs de cp :

cp
99999       97683
9999         2068
AA9A 9AA      125
9999-999      124
Name: count, dtype: int64

Motifs de telephone :

telephone
9999999999           66638
<AAAA>                5999
+99999999999          5301
99-99-99-99-99        4267
99.99.99.99.99        4261
99 99 99 99 99        4243
+99 9 99 99 99 99     4235
                      2000
                      2000
+999999999999          338
999999999              273
9999A99999             250
Name: count, dtype: int64

Motifs de pays :

pays
AA        97400
AAAAAA     1600
A           600
            400
Name: count, dtype: int64

Cellule 2 : Code postal (RQ-005) et anomalie A01

In [37]:
def conformite(serie, regex):
    """(testées, en échec) pour une expression régulière complète ; une valeur nulle est en échec."""
    ok = serie.fillna("").str.fullmatch(regex)
    return len(serie), int((~ok).sum())

# On teste uniquement les adresses françaises : les CP étrangers ont une autre forme
fr = b[b.pays == "FR"]
n, ko = conformite(fr.cp, r"[0-9]{5}")
print(f"RQ-005 : code postal à 5 chiffres, adresses FR : {ko} écarts sur {n} ({100*ko/n:.3f} %)")

print("\nA01 (zéro initial perdu) — les CP à 4 chiffres et leur ville :")
display(fr[fr.cp.fillna("").str.fullmatch(r"[0-9]{4}")]
          .groupby(["cp", "ville"]).size().sort_values(ascending=False).head(10))

RQ-005 : code postal à 5 chiffres, adresses FR : 1456 écarts sur 95437 (1.526 %)

A01 (zéro initial perdu) — les CP à 4 chiffres et leur ville :

cp    ville
1000  Bourg-en-Bresse      92
1100  Oyonnax              77
7100  Annonay              71
1700  Miribel              69
7200  Aubenas              67
1500  Ambérieu-en-Bugey    63
1120  Montluel             53
3200  Vichy                52
3000  Moulins              50
1360  Loyettes             44
dtype: int64

Cellule 3 : Téléphone

In [38]:
# Numéro français : 0 / +33 / 0033, puis 9 chiffres, séparés ou non par espace, point ou tiret
regex_fr   = r"(?:0|\+33 ?|0033 ?)[1-9](?:[ .-]?[0-9]{2}){4}"
# Numéro étranger valide : + indicatif autre que 33, puis 9 à 14 chiffres
regex_intl = r"\+(?!33)[1-9][0-9]{8,13}"
regex_telephone = f"{regex_fr}|{regex_intl}"

renseignes = b[b.telephone.notna() & (b.telephone.str.strip() != "")]
n, ko = conformite(renseignes.telephone, regex_telephone)
print(f"téléphone : {ko} écarts sur {n} numéros renseignés ({100*ko/n:.2f} %)")

rejets = renseignes.telephone[~renseignes.telephone.str.fullmatch(regex_telephone)]
print("\nMotifs des numéros rejetés :")
display(motif(rejets).value_counts())
print("Exemples :", rejets.head(6).tolist())

téléphone : 886 écarts sur 90001 numéros renseignés (0.98 %)

Motifs des numéros rejetés :

telephone
999999999      273
9999A99999     250
9999A999999    195
9999999999     168
Name: count, dtype: int64

Exemples : ['3397633710', '044915574', '3392463946', '061411425', '3379O165647', '3322O477042']

Cellule 4 : Pays : comparaison au référentiel

In [39]:
ref_pays = set(lire("SELECT code_pays FROM silver.ref_pays").code_pays)
hors = b[~b.pays.isin(ref_pays)]
print(f"pays hors référentiel : {len(hors)} sur {len(b)}")
display(hors.pays.value_counts(dropna=False).head(15))

pays hors référentiel : 3050 sur 100000

pays
France    1200
F          600
           400
fr         400
Frnace     400
UK          20
ZZ          10
EN          10
XX          10
Name: count, dtype: int64

# **US-04**

In [40]:
import pandas as pd
from sqlalchemy import create_engine, text

reader = create_engine("mysql+pymysql://reader:reader@mariadb:3306")  # lecture seule sur cif et crm
engine = create_engine("mysql+pymysql://root:root@mariadb:3306")      # écriture dans bronze et dq

BATCH = "L-2026-10-01"   # identifiant du lot

def lire(sql, eng=engine, **params):
    return pd.read_sql(text(sql), eng, params=params)

Charger le CIF depuis bronze

In [41]:
cif = lire("SELECT * FROM bronze.cif_clients WHERE _batch_id = :b", b=BATCH)
cif = cif[[c for c in cif.columns if c.startswith("column")]]   # on enlève les métadonnées

print("Lignes :", len(cif), "| Colonnes :", len(cif.columns))
display(cif.head())

Lignes : 40000 | Colonnes : 10

,column0,column1,column2,column3,column4,column5,column6,column7,column8,column9
0,K100040,LECLERCQ,Bernard,12/07/1963,49 rue Hoche,74100,ANNEMASSE,FR,0101389234,bernard.leclercq1957@orange.fr
1,K100056,DAVID,Romain,26/01/1970,58 AVENUE DU GÉNÉRAL DE GAULLE,07200,AUBENAS,FR,0455645409,romain.david4526@gmail.com
2,K100057,DURAND,Lucas,15/10/1941,7 rue Gambetta,69009,LYON,FR,0472738646,None
3,K100063,HUBERT,CATHERINE,23/11/1964,88 PASSAGE DES ARTS,69009,LYON,FR,0779731727,None
4,K100065,LOUIS,Éric,11/06/1971,118 rue du 8 Mai 1945,74700,SALLANCHES,FR,0414875598,None

Cellule 3 : Le profil de chaque colonne

In [42]:
def motif(s):
    """9 = un chiffre, A = une lettre : on voit la forme de la valeur."""
    return (s.fillna("<NULL>")
             .str.replace(r"[0-9]", "9", regex=True)
             .str.replace(r"[A-Za-z]", "A", regex=True))

profil = pd.DataFrame({
    "nuls":           cif.isna().sum(),
    "distincts":      cif.nunique(),
    "long_min":       cif.apply(lambda s: s.str.len().min()).astype("Int64"),
    "long_max":       cif.apply(lambda s: s.str.len().max()).astype("Int64"),
    "motif_dominant": cif.apply(lambda s: motif(s).value_counts().index[0]),
    "pct_motif":      cif.apply(lambda s: round(100 * motif(s).value_counts().iloc[0] / len(s), 1)),
})
profil

          nuls  distincts  long_min  long_max      motif_dominant  pct_motif
column0      0      40000         7         7             A999999      100.0
column1      0        731         3        31              AAAAAA       30.4
column2    645        180         3        10              AAAAAA       21.4
column3    645      21081        10        10          99/99/9999       98.4
column4      0       9811        11        31  99 AAA AA AAAAAAAA        4.4
column5      0        188         4         8               99999       99.1
column6      0        172         3        24                AAAA       16.7
column7      0          9         2         2                  AA      100.0
column8   6324      33676        10        10          9999999999       84.2
column9  18872      21128        18        35              <AAAA>       47.2

Cellule 4 : Les indices décisifs

In [43]:
print("column0 : commence toujours par", cif.column0.str[0].unique(), "| unique :", cif.column0.is_unique)
print("column1 : 100 % majuscules :", (cif.column1 == cif.column1.str.upper()).all(),
      "| formes juridiques (SARL, SA…) :", int(cif.column1.str.contains(r"\b(?:SARL|SAS|SA|EURL)\b", na=False).sum()))
print("column2 / column3 : nuls aux mêmes lignes :", int((cif.column2.isna() & cif.column3.isna()).sum()),
      "sur", int(cif.column2.isna().sum()))
d = pd.to_datetime(cif.column3, format="%d/%m/%Y", errors="coerce")
print("column3 : dates valides :", int(d.notna().sum()), "| de", d.min().date(), "à", d.max().date())
print("column4 : commence par un numéro :", int(cif.column4.str.match(r"\d+ ").sum()))
print("column5 : 5 chiffres :", int(cif.column5.str.fullmatch(r"\d{5}").sum()),
      "| 4 chiffres (zéro perdu) :", int(cif.column5.str.fullmatch(r"\d{4}").sum()))
print("column6 : exemples :", cif.column6.value_counts().head(3).index.tolist())
print("column7 : valeurs :", cif.column7.value_counts().head(5).to_dict())
print("column8 : 0 + 9 chiffres :", int(cif.column8.str.fullmatch(r"0\d{9}").sum()), "sur", int(cif.column8.notna().sum()))
print("column9 : contient @ :", int(cif.column9.str.contains("@", na=False).sum()), "sur", int(cif.column9.notna().sum()))

column0 : commence toujours par ['K'] | unique : True
column1 : 100 % majuscules : True | formes juridiques (SARL, SA…) : 486
column2 / column3 : nuls aux mêmes lignes : 645 sur 645
column3 : dates valides : 39355 | de 1938-08-04 à 2026-06-15
column4 : commence par un numéro : 40000
column5 : 5 chiffres : 39659 | 4 chiffres (zéro perdu) : 244
column6 : exemples : ['LYON', 'VILLEURBANNE', 'PARIS']
column7 : valeurs : {'FR': 39401, 'ES': 105, 'CH': 100, 'BE': 95, 'IT': 80}
column8 : 0 + 9 chiffres : 33676 sur 33676
column9 : contient @ : 21128 sur 21128

Cellule 5 : Le lien avec cif_compte

In [44]:
compte = lire("SELECT * FROM bronze.cif_compte WHERE _batch_id = :b", b=BATCH)
compte = compte[[c for c in compte.columns if c.startswith("column")]]

liens = [(a, k, round(100 * compte[a].isin(set(cif[k].dropna())).mean(), 1))
         for a in compte.columns for k in cif.columns]
pd.DataFrame(liens, columns=["colonne_compte", "colonne_clients", "pct_retrouvees"]) \
  .sort_values("pct_retrouvees", ascending=False).head(5)

   colonne_compte colonne_clients  pct_retrouvees
10        column1         column0           100.0
21        column2         column1             0.0
23        column2         column3             0.0
24        column2         column4             0.0
25        column2         column5             0.0

Cellule 6 : Le dictionnaire final

In [45]:
dictionnaire = pd.DataFrame([
    ["column0", "id_cif",                "VARCHAR(7)",        "40 000 distincts / 40 000, 0 nul ; motif K + 6 chiffres à 100 % ; retrouvé à 100 % dans cif_compte → clé primaire"],
    ["column1", "nom_ou_raison_sociale", "VARCHAR(120)",      "0 nul, 731 distincts, 3 à 31 car., 100 % majuscules ; contient des SARL/SA → nom ou entreprise"],
    ["column2", "prenom",                "VARCHAR(80)",       "645 nuls, sur les mêmes lignes que column3 (entreprises) ; 180 distincts, 3 à 10 car."],
    ["column3", "date_naissance",        "DATE (JJ/MM/AAAA)", "longueur toujours 10, motif 99/99/9999 ; 39 355 dates valides (1938 à 2026) ; 645 nuls = entreprises"],
    ["column4", "adresse",               "VARCHAR(120)",      "9 811 distincts, 11 à 31 car. ; numéro + type de voie (35 avenue des Platanes)"],
    ["column5", "code_postal",           "VARCHAR(10)",       "99,1 % au motif 99999 ; 188 distincts ; 244 à 4 chiffres (zéro perdu, A01)"],
    ["column6", "ville",                 "VARCHAR(80)",       "172 distincts, 3 à 24 car., en majuscules (LARGENTIERE, ANTIBES)"],
    ["column7", "code_pays",             "CHAR(2)",           "longueur toujours 2, motif AA à 100 %, 9 valeurs ; FR = 98,5 % → code ISO"],
    ["column8", "telephone",             "VARCHAR(25)",       "longueur toujours 10, 0 + 9 chiffres sur 100 % des valeurs renseignées ; 6 324 nuls"],
    ["column9", "email",                 "VARCHAR(120)",      "100 % des 21 128 valeurs renseignées contiennent @ ; 18 872 nuls (47 %)"],
], columns=["Colonne d'origine", "Nom proposé", "Type", "Justification chiffrée"])

pd.set_option("display.max_colwidth", None)
dictionnaire

,Colonne d'origine,Nom proposé,Type,Justification chiffrée
0,column0,id_cif,VARCHAR(7),"40 000 distincts / 40 000, 0 nul ; motif K + 6 chiffres à 100 % ; retrouvé à 100 % dans cif_compte → clé primaire"
1,column1,nom_ou_raison_sociale,VARCHAR(120),"0 nul, 731 distincts, 3 à 31 car., 100 % majuscules ; contient des SARL/SA → nom ou entreprise"
2,column2,prenom,VARCHAR(80),"645 nuls, sur les mêmes lignes que column3 (entreprises) ; 180 distincts, 3 à 10 car."
3,column3,date_naissance,DATE (JJ/MM/AAAA),"longueur toujours 10, motif 99/99/9999 ; 39 355 dates valides (1938 à 2026) ; 645 nuls = entreprises"
4,column4,adresse,VARCHAR(120),"9 811 distincts, 11 à 31 car. ; numéro + type de voie (35 avenue des Platanes)"
5,column5,code_postal,VARCHAR(10),"99,1 % au motif 99999 ; 188 distincts ; 244 à 4 chiffres (zéro perdu, A01)"
6,column6,ville,VARCHAR(80),"172 distincts, 3 à 24 car., en majuscules (LARGENTIERE, ANTIBES)"
7,column7,code_pays,CHAR(2),"longueur toujours 2, motif AA à 100 %, 9 valeurs ; FR = 98,5 % → code ISO"
8,column8,telephone,VARCHAR(25),"longueur toujours 10, 0 + 9 chiffres sur 100 % des valeurs renseignées ; 6 324 nuls"
9,column9,email,VARCHAR(120),100 % des 21 128 valeurs renseignées contiennent @ ; 18 872 nuls (47 %)

In [46]:
import pandas as pd
from sqlalchemy import create_engine, text

reader = create_engine("mysql+pymysql://reader:reader@mariadb:3306")  # lecture seule sur cif et crm
engine = create_engine("mysql+pymysql://root:root@mariadb:3306")      # écriture dans bronze et dq

BATCH = "L-2026-10-01"   # identifiant du lot

def lire(sql, eng=engine, **params):
    return pd.read_sql(text(sql), eng, params=params)

# **US-09**

Cellule 1 : Fixation des dates

In [47]:
DATE_REF       = "2026-10-01"   # date du lot L-2026-10-01 : « aujourd'hui » pour le calcul
COTISATION_MIN = "2026-07-01"   # 3 mois avant : une cotisation après cette date = « à jour »

Cellule 2 : Chargement les contrats

In [48]:
contrat = lire("""SELECT souscripteur_id, date_debut, date_fin, date_derniere_cotisation
                  FROM bronze.crm_contrat WHERE _batch_id = :b""", b=BATCH)


for c in ["date_debut", "date_fin", "date_derniere_cotisation"]:
    contrat[c] = pd.to_datetime(contrat[c], errors="coerce")

ref, cotisation = pd.Timestamp(DATE_REF), pd.Timestamp(COTISATION_MIN)
print("date de référence :", ref.date(), "| cotisation depuis :", cotisation.date())
print("contrats chargés :", len(contrat))

date de référence : 2026-10-01 | cotisation depuis : 2026-07-01
contrats chargés : 100000

Cellule 3 : Les trois définitions

In [49]:
# Un contrat est « en cours » s'il a commencé avant la date de réf. et finit après
en_cours = (contrat.date_debut <= ref) & (contrat.date_fin >= ref)
# Une cotisation est « à jour » si la dernière date de paiement est dans les 3 derniers mois
a_jour   = contrat.date_derniere_cotisation >= cotisation

# On compte des souscripteurs DISTINCTS (un client avec 3 contrats ne compte qu'une fois)
n_commerciale = contrat.souscripteur_id.nunique()
n_sinistres   = contrat[en_cours].souscripteur_id.nunique()
n_risques     = contrat[en_cours & a_jour].souscripteur_id.nunique()

print("Commerciale :", n_commerciale)
print("Sinistres   :", n_sinistres)
print("Risques     :", n_risques)

Commerciale : 50508
Sinistres   : 44116
Risques     : 38049

Cellule 4 : Le tableau des écarts

In [50]:
ecarts = pd.DataFrame({
    "direction":  ["Commerciale", "Sinistres", "Risques (CD-001)"],
    "definition": ["au moins un contrat",
                   "un contrat en cours au " + DATE_REF,
                   "contrat en cours ET cotisation depuis le " + COTISATION_MIN],
    "nb":         [n_commerciale, n_sinistres, n_risques],
})
ecarts["ecart_vs_CD001"] = ecarts.nb - n_risques
ecarts["ecart_pct"]      = (100 * ecarts.ecart_vs_CD001 / n_risques).round(1)
ecarts["rapport"]        = (ecarts.nb / ecarts.nb.max()).round(3)
ecarts

,direction,definition,nb,ecart_vs_CD001,ecart_pct,rapport
0,Commerciale,au moins un contrat,50508,12459,32.7,1.000
1,Sinistres,un contrat en cours au 2026-10-01,44116,6067,15.9,0.873
2,Risques (CD-001),contrat en cours ET cotisation depuis le 2026-07-01,38049,0,0.0,0.753

Cellule 5: Pourquoi CD-001 exclut des contrats en cours

In [51]:
sans_date = en_cours & contrat.date_derniere_cotisation.isna()
en_retard = en_cours & (contrat.date_derniere_cotisation < cotisation)
print("Contrats en cours :", int(en_cours.sum()))
print("  dont sans date de cotisation (NULL) :", int(sans_date.sum()))
print("  dont cotisation en retard (> 3 mois) :", int(en_retard.sum()))

Contrats en cours : 69243
  dont sans date de cotisation (NULL) : 6522
  dont cotisation en retard (> 3 mois) : 5675

# **US-05**

In [52]:
from sqlalchemy import text
import pandas as pd

with engine.connect() as conn:
    tables_bronze = pd.read_sql(
        text("""
            SELECT TABLE_NAME
            FROM information_schema.TABLES
            WHERE TABLE_SCHEMA = 'bronze'
            ORDER BY TABLE_NAME
        """),
        conn
    )

display(tables_bronze)

         TABLE_NAME
0       cif_clients
1        cif_compte
2          cif_pays
3        crm_client
4       crm_contrat
5      crm_sinistre
6  crm_type_contrat

In [54]:
from sqlalchemy import text
import pandas as pd

with engine.connect() as conn:
    colonnes = pd.read_sql(
        text("""
            SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = 'bronze'
              AND TABLE_NAME IN ('cif_clients', 'crm_client')
            ORDER BY TABLE_NAME, ORDINAL_POSITION
        """),
        conn
    )

display(colonnes)

     TABLE_NAME     COLUMN_NAME DATA_TYPE
0   cif_clients   bronze_row_id    bigint
1   cif_clients         column0   varchar
2   cif_clients         column1   varchar
3   cif_clients         column2   varchar
4   cif_clients         column3   varchar
5   cif_clients         column4   varchar
6   cif_clients         column5   varchar
7   cif_clients         column6   varchar
8   cif_clients         column7   varchar
9   cif_clients         column8   varchar
10  cif_clients         column9   varchar
11  cif_clients       _batch_id   varchar
12  cif_clients  _source_system   varchar
13  cif_clients    _ingested_at  datetime
14  cif_clients       _row_hash      char
15   crm_client   bronze_row_id    bigint
16   crm_client       client_id   varchar
17   crm_client   type_personne   varchar
18   crm_client             nom   varchar
19   crm_client          prenom   varchar
20   crm_client  raison_sociale   varchar
21   crm_client  date_naissance   varchar
22   crm_client         adresse   varchar
23   crm_client              cp   varchar
24   crm_client           ville   varchar
25   crm_client            pays   varchar
26   crm_client       telephone   varchar
27   crm_client           email   varchar
28   crm_client   date_creation   varchar
29   crm_client       _batch_id   varchar
30   crm_client  _source_system   varchar
31   crm_client    _ingested_at  datetime
32   crm_client       _row_hash      char

In [55]:
from sqlalchemy import text
import pandas as pd

with engine.connect() as conn:
    exemple_cif = pd.read_sql(
        text("""
            SELECT column0, column1, column2, column3, column4,
                   column5, column6, column7, column8, column9,
                   _source_system
            FROM bronze.cif_clients
            LIMIT 5
        """),
        conn
    )

display(exemple_cif)

,column0,column1,column2,column3,column4,column5,column6,column7,column8,column9,_source_system
0,K100040,LECLERCQ,Bernard,12/07/1963,49 rue Hoche,74100,ANNEMASSE,FR,0101389234,bernard.leclercq1957@orange.fr,cif
1,K100056,DAVID,Romain,26/01/1970,58 AVENUE DU GÉNÉRAL DE GAULLE,07200,AUBENAS,FR,0455645409,romain.david4526@gmail.com,cif
2,K100057,DURAND,Lucas,15/10/1941,7 rue Gambetta,69009,LYON,FR,0472738646,None,cif
3,K100063,HUBERT,CATHERINE,23/11/1964,88 PASSAGE DES ARTS,69009,LYON,FR,0779731727,None,cif
4,K100065,LOUIS,Éric,11/06/1971,118 rue du 8 Mai 1945,74700,SALLANCHES,FR,0414875598,None,cif

In [56]:
with engine.connect() as conn:
    exemple_crm = pd.read_sql(
        text("""
            SELECT client_id, type_personne, nom, prenom,
                   raison_sociale, date_naissance, adresse,
                   cp, ville, pays, telephone, email
            FROM bronze.crm_client
            LIMIT 5
        """),
        conn
    )

display(exemple_crm)

,client_id,type_personne,nom,prenom,raison_sociale,date_naissance,adresse,cp,ville,pays,telephone,email
0,A-1000,souscripteur,Thomas,Sandrine,None,1975-04-16,31 rue Anatole France,69300,Caluire-et-Cuire,FR,0346234195,sandrine.thomas1093@free.fr
1,A-10000,assure,Leroy,Karim,None,1942-03-02,81 rue du Moulin,73000,Chambéry,FR,0212942708,contact@batimentgiraudsa6308.fr
2,A-10001,prospect,Dumas,Zoé,None,1980-11-02,16 rue de Provence,71000,Mâcon,,None,None
3,A-10002,souscripteur,Denis,Emma,None,2009-07-23,45 avenue du Général de Gaulle,69009,Saint-Étienne,FR,0129310237,None
4,A-10003,prospect,Perrin,Catherine,None,1957-09-02,88 rue des Jardins,69100,Villeurbanne,FR,+33582679882,romain.durand3630@free.fr

In [57]:
from sqlalchemy import text
import pandas as pd

requete = """
SELECT
    COUNT(*) AS nb_lignes_cif,
    COUNT(DISTINCT column0) AS nb_ids_cif,
    SUM(column1 IS NOT NULL AND TRIM(column1) <> '') AS noms_renseignes,
    SUM(column2 IS NOT NULL AND TRIM(column2) <> '') AS prenoms_renseignes,
    SUM(column9 IS NOT NULL AND TRIM(column9) <> '') AS emails_renseignes
FROM bronze.cif_clients
"""

with engine.connect() as conn:
    resultat = pd.read_sql(text(requete), conn)

display(resultat)

,nb_lignes_cif,nb_ids_cif,noms_renseignes,prenoms_renseignes,emails_renseignes
0,40000,40000,40000.0,39355.0,21128.0

In [58]:
from sqlalchemy import text
import pandas as pd

with engine.connect() as conn:
    verification = pd.read_sql(
        text("""
            SELECT
                COUNT(*) AS total_lignes,
                COUNT(column0) AS ids_non_nuls,
                COUNT(DISTINCT column0) AS ids_distincts,
                SUM(column1 IS NULL OR TRIM(column1) = '') AS noms_vides,
                SUM(column2 IS NULL OR TRIM(column2) = '') AS prenoms_vides,
                SUM(column9 IS NULL OR TRIM(column9) = '') AS emails_vides
            FROM bronze.cif_clients
        """),
        conn
    )

display(verification)

,total_lignes,ids_non_nuls,ids_distincts,noms_vides,prenoms_vides,emails_vides
0,40000,40000,40000,0.0,645.0,18872.0

In [59]:
with engine.connect() as conn:
    test = pd.read_sql(
        text("""
            SELECT *
            FROM bronze.cif_clients
            LIMIT 3
        """),
        conn
    )

display(test)
print("Nombre de lignes retournées :", len(test))

,bronze_row_id,column0,column1,column2,column3,column4,column5,column6,column7,column8,column9,_batch_id,_source_system,_ingested_at,_row_hash
0,1,K100040,LECLERCQ,Bernard,12/07/1963,49 rue Hoche,74100,ANNEMASSE,FR,0101389234,bernard.leclercq1957@orange.fr,L-2026-10-01,cif,2026-10-21 11:38:36,fe1d3d2030ff65ef
1,2,K100056,DAVID,Romain,26/01/1970,58 AVENUE DU GÉNÉRAL DE GAULLE,07200,AUBENAS,FR,0455645409,romain.david4526@gmail.com,L-2026-10-01,cif,2026-10-21 11:38:36,cac38aa00ab09b7e
2,3,K100057,DURAND,Lucas,15/10/1941,7 rue Gambetta,69009,LYON,FR,0472738646,None,L-2026-10-01,cif,2026-10-21 11:38:36,dba965d433417b46

Nombre de lignes retournées : 3

In [60]:
with engine.connect() as conn:
    stats_cif = pd.read_sql(
        text("""
            SELECT
                COUNT(*) AS total_lignes,
                COUNT(column0) AS ids_renseignes,
                COUNT(DISTINCT column0) AS ids_distincts,
                SUM(column1 IS NULL OR TRIM(column1) = '') AS noms_vides,
                SUM(column2 IS NULL OR TRIM(column2) = '') AS prenoms_vides,
                SUM(column9 IS NULL OR TRIM(column9) = '') AS emails_vides
            FROM bronze.cif_clients
        """),
        conn
    )

display(stats_cif)

,total_lignes,ids_renseignes,ids_distincts,noms_vides,prenoms_vides,emails_vides
0,40000,40000,40000,0.0,645.0,18872.0

In [61]:
with engine.connect() as conn:
    print("Connexion :", conn.execute(text("SELECT 1")).scalar())

    print("Comptage direct :", conn.execute(
        text("SELECT COUNT(*) FROM bronze.cif_clients")
    ).scalar())

    print("Comptage avec identifiant :", conn.execute(
        text("SELECT COUNT(column0) FROM bronze.cif_clients")
    ).scalar())

Connexion : 1
Comptage direct : 40000
Comptage avec identifiant : 40000

In [62]:
with engine.connect() as conn:
    comparaison_ids = pd.read_sql(
        text("""
            SELECT
                (SELECT COUNT(*)
                 FROM bronze.cif_clients) AS total_cif,

                (SELECT COUNT(*)
                 FROM bronze.crm_client) AS total_crm,

                (SELECT COUNT(*)
                 FROM bronze.cif_clients c
                 INNER JOIN bronze.crm_client r
                    ON c.column0 = r.client_id
                ) AS correspondances_ids
        """),
        conn
    )

display(comparaison_ids)

   total_cif  total_crm  correspondances_ids
0      40000     100000                    0

In [63]:
with engine.connect() as conn:
    for table in ["cif_clients", "crm_client"]:
        total = conn.execute(
            text(f"SELECT COUNT(*) FROM bronze.{table}")
        ).scalar()

        print(f"{table} : {total} lignes")

cif_clients : 40000 lignes
crm_client : 100000 lignes

In [64]:
with engine.connect() as conn:
    communs = conn.execute(text("""
        SELECT COUNT(*)
        FROM bronze.cif_clients c
        INNER JOIN bronze.crm_client r
            ON c.column0 = r.client_id
    """)).scalar()

    print("Identifiants communs CIF-CRM :", communs)

Identifiants communs CIF-CRM : 0

In [65]:
with engine.connect() as conn:
    resultat = conn.execute(text("""
        SELECT column0, column1, column2, column3
        FROM bronze.cif_clients
        LIMIT 5
    """)).fetchall()

    for ligne in resultat:
        print(ligne)

('K100040', 'LECLERCQ', 'Bernard', '12/07/1963')
('K100056', 'DAVID', 'Romain', '26/01/1970')
('K100057', 'DURAND', 'Lucas', '15/10/1941')
('K100063', 'HUBERT', 'CATHERINE', '23/11/1964')
('K100065', 'LOUIS', 'Éric', '11/06/1971')