**US-01**

In [7]:
import pandas as pd
from sqlalchemy import create_engine, text

engine = create_engine("mysql+pymysql://root:root@mariadb:3306")     # écriture (bronze, dq)
reader = create_engine("mysql+pymysql://reader:reader@mariadb:3306")  # lecture seule des sources

def lire(sql, eng=reader):
    """Exécute une requête SELECT et renvoie un DataFrame."""
    return pd.read_sql(text(sql), eng)

lire("SELECT COUNT(*) AS n FROM crm.client")

        n
0  100000

In [8]:
# Tables et nombre de colonnes
cols = lire("""
    SELECT table_schema AS base, table_name AS `table`, COUNT(*) AS colonnes
    FROM information_schema.columns
    WHERE table_schema IN ('cif','crm')
    GROUP BY table_schema, table_name""")

# Clé primaire
cles = lire("""
    SELECT table_schema AS base, table_name AS `table`,
           GROUP_CONCAT(column_name ORDER BY ordinal_position) AS cle_primaire
    FROM information_schema.key_column_usage
    WHERE table_schema IN ('cif','crm') AND constraint_name = 'PRIMARY'
    GROUP BY table_schema, table_name""")

inventaire = cols.merge(cles, how="left", on=["base", "table"])

# Comptage exact (table_rows n'est qu'une estimation)
inventaire["lignes"] = [int(lire(f"SELECT COUNT(*) AS n FROM {b}.{t}").n[0])
                        for b, t in zip(inventaire.base, inventaire.table)]

inventaire = inventaire.sort_values(["base", "table"], ascending=[False, True]).reset_index(drop=True)
inventaire

  base         table  colonnes cle_primaire  lignes
0  crm        client        13    client_id  100000
1  crm       contrat         9   contrat_id  100000
2  crm      sinistre        10  sinistre_id  100000
3  crm  type_contrat         3    code_type      12
4  cif       clients        10      column0   40000
5  cif        compte         4      column0   45000
6  cif          pays         2    code_pays     250

In [9]:
sans_pk = inventaire[inventaire.cle_primaire.isna()][["base", "table"]]
print(f"{len(sans_pk)} table(s) sans clé primaire")
sans_pk

0 table(s) sans clé primaire

Empty DataFrame
Columns: [base, table]
Index: []

In [10]:
nuls = []
for b, t in zip(inventaire.base, inventaire.table):
    df = lire(f"SELECT * FROM {b}.{t}")
    n = df.isna().sum()
    nuls.append({
        "base": b, "table": t,
        "total_nuls": int(n.sum()),
        "colonnes_avec_nuls": int((n > 0).sum()),
        "colonne_max_nuls": n.idxmax() if n.max() > 0 else "-",
        "nb_nuls_max": int(n.max()),
    })
nuls = pd.DataFrame(nuls)
nuls

,base,table,total_nuls,colonnes_avec_nuls,colonne_max_nuls,nb_nuls_max
0,crm,client,133918,6,raison_sociale,95723
1,crm,contrat,7460,1,date_derniere_cotisation,7460
2,crm,sinistre,0,0,-,0
3,crm,type_contrat,0,0,-,0
4,cif,clients,26486,4,column9,18872
5,cif,compte,0,0,-,0
6,cif,pays,0,0,-,0

In [11]:
doublons = []
for b, t, pk in zip(inventaire.base, inventaire.table, inventaire.cle_primaire):
    cle = f"CONCAT_WS('|', {pk})"
    d = lire(f"SELECT COUNT(*) - COUNT(DISTINCT {cle}) AS n FROM {b}.{t}").n[0]
    doublons.append({"base": b, "table": t, "doublons_cle": int(d)})
doublons = pd.DataFrame(doublons)
doublons

  base         table  doublons_cle
0  crm        client             0
1  crm       contrat             0
2  crm      sinistre             0
3  crm  type_contrat             0
4  cif       clients             0
5  cif        compte             0
6  cif          pays             0

In [14]:
# Cellule 6 — Une particularité par table (les nombres en SQL, le texte en Python)
def val(sql):
    """Renvoie la première ligne d'une requête sous forme de dictionnaire."""
    return lire(sql).iloc[0].to_dict()

c   = val("SELECT SUM(raison_sociale IS NOT NULL) AS pm FROM crm.client")
ct  = val("SELECT SUM(assure_id = '0') AS sentinelle FROM crm.contrat")
s   = val("SELECT COUNT(DISTINCT canal_saisie) AS canaux, COUNT(DISTINCT contrat_id) AS contrats FROM crm.sinistre")
tc  = val("SELECT COUNT(*) AS types, COUNT(DISTINCT branche) AS branches FROM crm.type_contrat")
cpt = val("SELECT COUNT(*) AS comptes, COUNT(DISTINCT column1) AS ids FROM cif.compte")
p   = val("SELECT COUNT(*) AS pays FROM cif.pays")

particularites = pd.DataFrame([
    {"base": "crm", "table": "client",
     "particularite": f"{int(c['pm'])} personnes morales (raison_sociale renseignée, nom vide)"},
    {"base": "crm", "table": "contrat",
     "particularite": f"{int(ct['sentinelle'])} contrats avec assure_id = '0' (valeur sentinelle)"},
    {"base": "crm", "table": "sinistre",
     "particularite": f"{int(s['canaux'])} canaux de saisie, {int(s['contrats'])} contrats distincts concernés"},
    {"base": "crm", "table": "type_contrat",
     "particularite": f"{int(tc['types'])} types répartis sur {int(tc['branches'])} branches"},
    {"base": "cif", "table": "clients",
     "particularite": "10 colonnes aux noms anonymes (column0 à column9), sans documentation"},
    {"base": "cif", "table": "compte",
     "particularite": f"{int(cpt['comptes'])} comptes pour {int(cpt['ids'])} identifiants CIF distincts"},
    {"base": "cif", "table": "pays",
     "particularite": f"{int(p['pays'])} pays dans le référentiel"},
])
particularites

,base,table,particularite
0,crm,client,"4277 personnes morales (raison_sociale renseignée, nom vide)"
1,crm,contrat,40000 contrats avec assure_id = '0' (valeur sentinelle)
2,crm,sinistre,"4 canaux de saisie, 62782 contrats distincts concernés"
3,crm,type_contrat,12 types répartis sur 3 branches
4,cif,clients,"10 colonnes aux noms anonymes (column0 à column9), sans documentation"
5,cif,compte,45000 comptes pour 40000 identifiants CIF distincts
6,cif,pays,250 pays dans le référentiel

In [15]:
us01 = (inventaire
        .merge(nuls, on=["base", "table"])
        .merge(doublons, on=["base", "table"])
        .merge(particularites, on=["base", "table"]))

def observation(r):
    txt = f"{r.doublons_cle} doublon de clé"
    if r.total_nuls:
        txt += f" ; {r.total_nuls} nuls sur {r.colonnes_avec_nuls} colonne(s), max sur {r.colonne_max_nuls} ({r.nb_nuls_max})"
    else:
        txt += " ; aucun nul"
    return txt + f" ; {r.particularite}"

us01["Observation chiffrée"] = us01.apply(observation, axis=1)

livrable_us01 = us01.rename(columns={"base": "Source", "table": "Table",
                                     "lignes": "Lignes", "cle_primaire": "Clé primaire"})[
    ["Source", "Table", "Lignes", "Clé primaire", "Observation chiffrée"]]

pd.set_option("display.max_colwidth", None)
livrable_us01

,Source,Table,Lignes,Clé primaire,Observation chiffrée
0,crm,client,100000,client_id,"0 doublon de clé ; 133918 nuls sur 6 colonne(s), max sur raison_sociale (95723) ; 4277 personnes morales (raison_sociale renseignée, nom vide)"
1,crm,contrat,100000,contrat_id,"0 doublon de clé ; 7460 nuls sur 1 colonne(s), max sur date_derniere_cotisation (7460) ; 40000 contrats avec assure_id = '0' (valeur sentinelle)"
2,crm,sinistre,100000,sinistre_id,"0 doublon de clé ; aucun nul ; 4 canaux de saisie, 62782 contrats distincts concernés"
3,crm,type_contrat,12,code_type,0 doublon de clé ; aucun nul ; 12 types répartis sur 3 branches
4,cif,clients,40000,column0,"0 doublon de clé ; 26486 nuls sur 4 colonne(s), max sur column9 (18872) ; 10 colonnes aux noms anonymes (column0 à column9), sans documentation"
5,cif,compte,45000,column0,0 doublon de clé ; aucun nul ; 45000 comptes pour 40000 identifiants CIF distincts
6,cif,pays,250,code_pays,0 doublon de clé ; aucun nul ; 250 pays dans le référentiel