**US-01**

In [7]:
import pandas as pd
from sqlalchemy import create_engine, text

engine = create_engine("mysql+pymysql://root:root@mariadb:3306")     # écriture (bronze, dq)
reader = create_engine("mysql+pymysql://reader:reader@mariadb:3306")  # lecture seule des sources

def lire(sql, eng=reader):
    """Exécute une requête SELECT et renvoie un DataFrame."""
    return pd.read_sql(text(sql), eng)

lire("SELECT COUNT(*) AS n FROM crm.client")

        n
0  100000

In [8]:
# Tables et nombre de colonnes
cols = lire("""
    SELECT table_schema AS base, table_name AS `table`, COUNT(*) AS colonnes
    FROM information_schema.columns
    WHERE table_schema IN ('cif','crm')
    GROUP BY table_schema, table_name""")

# Clé primaire
cles = lire("""
    SELECT table_schema AS base, table_name AS `table`,
           GROUP_CONCAT(column_name ORDER BY ordinal_position) AS cle_primaire
    FROM information_schema.key_column_usage
    WHERE table_schema IN ('cif','crm') AND constraint_name = 'PRIMARY'
    GROUP BY table_schema, table_name""")

inventaire = cols.merge(cles, how="left", on=["base", "table"])

# Comptage exact (table_rows n'est qu'une estimation)
inventaire["lignes"] = [int(lire(f"SELECT COUNT(*) AS n FROM {b}.{t}").n[0])
                        for b, t in zip(inventaire.base, inventaire.table)]

inventaire = inventaire.sort_values(["base", "table"], ascending=[False, True]).reset_index(drop=True)
inventaire

  base         table  colonnes cle_primaire  lignes
0  crm        client        13    client_id  100000
1  crm       contrat         9   contrat_id  100000
2  crm      sinistre        10  sinistre_id  100000
3  crm  type_contrat         3    code_type      12
4  cif       clients        10      column0   40000
5  cif        compte         4      column0   45000
6  cif          pays         2    code_pays     250

In [9]:
sans_pk = inventaire[inventaire.cle_primaire.isna()][["base", "table"]]
print(f"{len(sans_pk)} table(s) sans clé primaire")
sans_pk

0 table(s) sans clé primaire

Empty DataFrame
Columns: [base, table]
Index: []

In [10]:
nuls = []
for b, t in zip(inventaire.base, inventaire.table):
    df = lire(f"SELECT * FROM {b}.{t}")
    n = df.isna().sum()
    nuls.append({
        "base": b, "table": t,
        "total_nuls": int(n.sum()),
        "colonnes_avec_nuls": int((n > 0).sum()),
        "colonne_max_nuls": n.idxmax() if n.max() > 0 else "-",
        "nb_nuls_max": int(n.max()),
    })
nuls = pd.DataFrame(nuls)
nuls

,base,table,total_nuls,colonnes_avec_nuls,colonne_max_nuls,nb_nuls_max
0,crm,client,133918,6,raison_sociale,95723
1,crm,contrat,7460,1,date_derniere_cotisation,7460
2,crm,sinistre,0,0,-,0
3,crm,type_contrat,0,0,-,0
4,cif,clients,26486,4,column9,18872
5,cif,compte,0,0,-,0
6,cif,pays,0,0,-,0

In [11]:
doublons = []
for b, t, pk in zip(inventaire.base, inventaire.table, inventaire.cle_primaire):
    cle = f"CONCAT_WS('|', {pk})"
    d = lire(f"SELECT COUNT(*) - COUNT(DISTINCT {cle}) AS n FROM {b}.{t}").n[0]
    doublons.append({"base": b, "table": t, "doublons_cle": int(d)})
doublons = pd.DataFrame(doublons)
doublons

  base         table  doublons_cle
0  crm        client             0
1  crm       contrat             0
2  crm      sinistre             0
3  crm  type_contrat             0
4  cif       clients             0
5  cif        compte             0
6  cif          pays             0

In [14]:
# Cellule 6 — Une particularité par table (les nombres en SQL, le texte en Python)
def val(sql):
    """Renvoie la première ligne d'une requête sous forme de dictionnaire."""
    return lire(sql).iloc[0].to_dict()

c   = val("SELECT SUM(raison_sociale IS NOT NULL) AS pm FROM crm.client")
ct  = val("SELECT SUM(assure_id = '0') AS sentinelle FROM crm.contrat")
s   = val("SELECT COUNT(DISTINCT canal_saisie) AS canaux, COUNT(DISTINCT contrat_id) AS contrats FROM crm.sinistre")
tc  = val("SELECT COUNT(*) AS types, COUNT(DISTINCT branche) AS branches FROM crm.type_contrat")
cpt = val("SELECT COUNT(*) AS comptes, COUNT(DISTINCT column1) AS ids FROM cif.compte")
p   = val("SELECT COUNT(*) AS pays FROM cif.pays")

particularites = pd.DataFrame([
    {"base": "crm", "table": "client",
     "particularite": f"{int(c['pm'])} personnes morales (raison_sociale renseignée, nom vide)"},
    {"base": "crm", "table": "contrat",
     "particularite": f"{int(ct['sentinelle'])} contrats avec assure_id = '0' (valeur sentinelle)"},
    {"base": "crm", "table": "sinistre",
     "particularite": f"{int(s['canaux'])} canaux de saisie, {int(s['contrats'])} contrats distincts concernés"},
    {"base": "crm", "table": "type_contrat",
     "particularite": f"{int(tc['types'])} types répartis sur {int(tc['branches'])} branches"},
    {"base": "cif", "table": "clients",
     "particularite": "10 colonnes aux noms anonymes (column0 à column9), sans documentation"},
    {"base": "cif", "table": "compte",
     "particularite": f"{int(cpt['comptes'])} comptes pour {int(cpt['ids'])} identifiants CIF distincts"},
    {"base": "cif", "table": "pays",
     "particularite": f"{int(p['pays'])} pays dans le référentiel"},
])
particularites

,base,table,particularite
0,crm,client,"4277 personnes morales (raison_sociale renseignée, nom vide)"
1,crm,contrat,40000 contrats avec assure_id = '0' (valeur sentinelle)
2,crm,sinistre,"4 canaux de saisie, 62782 contrats distincts concernés"
3,crm,type_contrat,12 types répartis sur 3 branches
4,cif,clients,"10 colonnes aux noms anonymes (column0 à column9), sans documentation"
5,cif,compte,45000 comptes pour 40000 identifiants CIF distincts
6,cif,pays,250 pays dans le référentiel

us01 = (inventaire
        .merge(nuls, on=["base", "table"])
        .merge(doublons, on=["base", "table"])
        .merge(particularites, on=["base", "table"]))

def observation(r):
    txt = f"{r.doublons_cle} doublon de clé"
    if r.total_nuls:
        txt += f" ; {r.total_nuls} nuls sur {r.colonnes_avec_nuls} colonne(s), max sur {r.colonne_max_nuls} ({r.nb_nuls_max})"
    else:
        txt += " ; aucun nul"
    return txt + f" ; {r.particularite}"

us01["Observation chiffrée"] = us01.apply(observation, axis=1)

livrable_us01 = us01.rename(columns={"base": "Source", "table": "Table",
                                     "lignes": "Lignes", "cle_primaire": "Clé primaire"})[
    ["Source", "Table", "Lignes", "Clé primaire", "Observation chiffrée"]]

pd.set_option("display.max_colwidth", None)
livrable_us01

**US-02**

Connexions et paramètres

In [1]:
import pandas as pd
from sqlalchemy import create_engine, text

reader = create_engine("mysql+pymysql://reader:reader@mariadb:3306")  # lecture seule sur cif et crm
engine = create_engine("mysql+pymysql://root:root@mariadb:3306")      # écriture dans bronze et dq

BATCH = "L-2026-10-01"   # identifiant du lot

def lire(sql, eng=engine):
    return pd.read_sql(text(sql), eng)

def executer(sql, **params):
    with engine.begin() as c:
        c.execute(text(sql), params)

SOURCES = [("crm", "client",       "crm_client"),
           ("crm", "contrat",      "crm_contrat"),
           ("crm", "type_contrat", "crm_type_contrat"),
           ("crm", "sinistre",     "crm_sinistre"),
           ("cif", "clients",      "cif_clients"),
           ("cif", "compte",       "cif_compte"),
           ("cif", "pays",         "cif_pays")]

Vérifier que le compte reader est bien en lecture seule

In [2]:
# 1. Ses droits
display(lire("SHOW GRANTS FOR 'reader'@'%'"))

# 2. Il peut lire
print("Lecture OK :", lire("SELECT COUNT(*) AS n FROM crm.client", reader).n[0], "lignes")

# 3. Il ne peut pas écrire (WHERE 1=0 : ne toucherait aucune ligne, même si c'était autorisé)
try:
    with reader.begin() as c:
        c.execute(text("DELETE FROM crm.type_contrat WHERE 1=0"))
    print("❌ PROBLÈME : reader a pu écrire")
except Exception as e:
    print("✅ Écriture refusée pour reader :", str(e.orig)[:80])

                                 Grants for reader@%
0  GRANT USAGE ON *.* TO `reader`@`%` IDENTIFIED ...
1            GRANT SELECT ON `cif`.* TO `reader`@`%`
2            GRANT SELECT ON `crm`.* TO `reader`@`%`

Lecture OK : 100000 lignes
✅ Écriture refusée pour reader : (1142, "DELETE command denied to user 'reader'@'172.20.0.3' for table `crm`.`typ

La fonction d’ingestion

In [3]:
def ingerer(base, table, cible):
    # 1. Lire la source avec le compte lecture seule.
    #    coerce_float=False : 184.10 reste 184.10 (sinon il devient 184.1 et la porte B échoue)
    #    .astype("string") : tout en texte, bronze ne transforme rien
    df = pd.read_sql(text(f"SELECT * FROM {base}.{table}"), reader,
                     coerce_float=False).astype("string")
    df = df.astype(object).where(df.notna(), None)          # les NULL restent NULL

    # 2. Empreinte de chaque ligne, calculée AVANT d'ajouter les métadonnées
    h = pd.util.hash_pandas_object(df.fillna("\\N").astype(str), index=False)
    df["_row_hash"] = [f"{v:016x}" for v in h]              # 16 caractères hexadécimaux

    # 3. Métadonnées (_ingested_at est rempli par MariaDB)
    df["_batch_id"] = BATCH
    df["_source_system"] = base

    # 4. Idempotence : on supprime d'abord ce lot, puis on le réinsère
    #    → relancer donne le même résultat, sans doublon
    with engine.begin() as c:
        c.execute(text(f"DELETE FROM bronze.{cible} WHERE _batch_id = :b"), {"b": BATCH})
        df.to_sql(cible, c, schema="bronze", if_exists="append",
                  index=False, chunksize=10_000)
    return len(df)

Lancer l’ingestion des 7 tables

In [4]:
# Déclarer le lot comme « en cours »
executer("""INSERT INTO dq.lot_ingestion (batch_id, statut) VALUES (:b, 'EN_COURS')
            ON DUPLICATE KEY UPDATE statut = 'EN_COURS', finished_at = NULL""", b=BATCH)

for base, table, cible in SOURCES:
    n = ingerer(base, table, cible)
    print(f"{base}.{table:<13} → bronze.{cible:<17} {n:>7} lignes")

# Clore le lot
executer("UPDATE dq.lot_ingestion SET statut = 'TERMINE', finished_at = NOW() WHERE batch_id = :b", b=BATCH)

crm.client        → bronze.crm_client         100000 lignes
crm.contrat       → bronze.crm_contrat        100000 lignes
crm.type_contrat  → bronze.crm_type_contrat       12 lignes
crm.sinistre      → bronze.crm_sinistre       100000 lignes
cif.clients       → bronze.cif_clients         40000 lignes
cif.compte        → bronze.cif_compte          45000 lignes
cif.pays          → bronze.cif_pays              250 lignes

Vérification : une ligne bronze par ligne source + les 4 métadonnées remplies (RQ-022)

In [5]:
controle = []
for base, table, cible in SOURCES:
    r = lire(f"""
        SELECT COUNT(*) AS bronze,
               SUM(_batch_id IS NULL OR _source_system IS NULL
                   OR _ingested_at IS NULL OR _row_hash IS NULL) AS metadonnee_manquante
        FROM bronze.{cible} WHERE _batch_id = '{BATCH}'""").iloc[0]
    src = lire(f"SELECT COUNT(*) AS n FROM {base}.{table}", reader).n[0]
    controle.append({"table": cible, "source": int(src), "bronze": int(r.bronze),
                     "ecart": int(r.bronze - src),
                     "metadonnee_manquante": int(r.metadonnee_manquante or 0)})
controle = pd.DataFrame(controle)
controle

              table  source  bronze  ecart  metadonnee_manquante
0        crm_client  100000  100000      0                     0
1       crm_contrat  100000  100000      0                     0
2  crm_type_contrat      12      12      0                     0
3      crm_sinistre  100000  100000      0                     0
4       cif_clients   40000   40000      0                     0
5        cif_compte   45000   45000      0                     0
6          cif_pays     250     250      0                     0

relancer le même lot ne crée aucun doublon

In [6]:
avant = lire("SELECT COUNT(*) AS n FROM bronze.crm_client").n[0]
ingerer("crm", "client", "crm_client")          # on relance le même lot
apres = lire("SELECT COUNT(*) AS n FROM bronze.crm_client").n[0]
print(f"Avant relance : {avant} · après relance : {apres} · doublons créés : {apres - avant}")

Avant relance : 100000 · après relance : 100000 · doublons créés : 0

Visualisation de la table bronze.crm_client

In [7]:
lire("SELECT client_id, nom, cp, pays, _batch_id, _source_system, _ingested_at, _row_hash "
     "FROM bronze.crm_client LIMIT 5")

,client_id,nom,cp,pays,_batch_id,_source_system,_ingested_at,_row_hash
0,A-1000,Thomas,69300,FR,L-2026-10-01,crm,2026-10-14 19:56:52,8fe9e59d3f5268ea
1,A-10000,Leroy,73000,FR,L-2026-10-01,crm,2026-10-14 19:56:52,bf96f99ffb10ed08
2,A-10001,Dumas,71000,,L-2026-10-01,crm,2026-10-14 19:56:52,5471aff6d3a407b8
3,A-10002,Denis,69009,FR,L-2026-10-01,crm,2026-10-14 19:56:52,4ac5023b52ef397a
4,A-10003,Perrin,69100,FR,L-2026-10-01,crm,2026-10-14 19:56:52,e33662a2cdbedbb2