# **US-10**

Cellule 1 : Connexions et paramètres

In [2]:
import os
import pandas as pd
import great_expectations as gx
from sqlalchemy import create_engine, text

engine = create_engine("mysql+pymysql://root:root@mariadb:3306")

def lire(sql, eng=engine, **params):
    return pd.read_sql(text(sql), eng, params=params)

# PARAMÈTRES : couche et lot testés. Pour silver, on changera seulement BASE.
BATCH = "L-2026-10-01"
BASE  = "bronze"

Cellule 2 : Le projet Great Expectations

In [3]:
DOSSIER_GE = "/home/jovyan/work/reports/ge" if os.path.isdir("/home/jovyan/work") else "reports/ge"
os.makedirs(DOSSIER_GE, exist_ok=True)

context    = gx.get_context(project_root_dir=DOSSIER_GE)
datasource = context.sources.add_or_update_pandas(name="assurconnect")
print("GE", gx.__version__, "| projet :", DOSSIER_GE)

GE 0.18.19 | projet : /home/jovyan/work/reports/ge

Cellule 3 : Le catalogue des règles

In [4]:
REGLES = lire("SELECT rule_id, libelle, dimension, severite, seuil_min FROM dq.regle").set_index("rule_id")
print(len(REGLES), "règles dans dq.regle")
display(REGLES)

def mostly(rule_id):
    """Seuil GE (entre 0 et 1) = seuil_min de la règle (en %)."""
    return float(REGLES.loc[rule_id, "seuil_min"]) / 100

CODES_PAYS = sorted(lire("SELECT code_pays FROM silver.ref_pays").code_pays)
print(len(CODES_PAYS), "codes pays de référence")

25 règles dans dq.regle

,libelle,dimension,severite,seuil_min
rule_id,,,,
RQ-001,La date de fin d'un contrat est postérieure à ...,Cohérence,BLOQUANTE,100.0
RQ-002,Un souscripteur personne physique a 18 ans ou ...,Validité métier,BLOQUANTE,100.0
RQ-003,Le téléphone d'un souscripteur est renseigné (...,Complétude,AVERTISSEMENT,98.0
RQ-004,"Pour une adresse en France, le téléphone respe...",Validité format,AVERTISSEMENT,98.0
RQ-005,"Pour une adresse en France, le code postal com...",Validité format,AVERTISSEMENT,98.0
RQ-006,"Pour une adresse en France, le couple code pos...",Exactitude,AVERTISSEMENT,98.0
RQ-007,Le pays (code ISO à deux lettres) appartient à...,Intégrité référentielle,BLOQUANTE,100.0
RQ-008,L'adresse e-mail respecte un motif valide,Validité format,AVERTISSEMENT,98.0
RQ-009,"Le type de personne vaut prospect, souscripteu...",Validité domaine,BLOQUANTE,100.0
RQ-010,"La durée de garantie vaut 12, 24, 36 ou 60 mois",Validité domaine,BLOQUANTE,100.0
RQ-011,Le type de contrat existe dans type_contrat,Intégrité référentielle,BLOQUANTE,100.0
RQ-012,Le souscripteur d'un contrat existe dans le cl...,Intégrité référentielle,BLOQUANTE,100.0
RQ-013,L'assuré d'un contrat existe dans le client ; ...,Intégrité référentielle,BLOQUANTE,100.0
RQ-014,"Adresse de sinistre : format valide, rapproché...","Précision, cohérence",BLOQUANTE,100.0
RQ-015,Un prospect n'a aucun contrat,Cohérence de statut,BLOQUANTE,100.0
RQ-016,Un souscripteur a au moins un contrat,Cohérence de statut,AVERTISSEMENT,98.0
RQ-017,La date de survenance d'un sinistre est compri...,Cohérence inter-tables,BLOQUANTE,100.0
RQ-018,Client actif : contrat en cours ET cotisation ...,Cohérence de définition,BLOQUANTE,100.0
RQ-019,Une personne n'a qu'un seul identifiant client...,Unicité,BLOQUANTE,100.0
RQ-020,Les clés primaires sont uniques et jamais nulles,Unicité,BLOQUANTE,100.0
RQ-021,Réconciliation source vers bronze : mêmes comp...,"Complétude, intégrité",BLOQUANTE,100.0
RQ-022,"Chaque ligne bronze porte lot, source, horodat...",Traçabilité,BLOQUANTE,100.0
RQ-023,Chaque ligne silver et gold référence sa ligne...,Traçabilité,BLOQUANTE,100.0
RQ-024,Conservation : lignes silver + lignes rejetées...,Complétude,BLOQUANTE,100.0
RQ-025,Réconciliation gold vers CRM : même comptage e...,Intégrité,BLOQUANTE,100.0

250 codes pays de référence

Cellule 4 : Charger et préparer les tables

In [5]:
# Dictionnaire de l'US-04 : on renomme les colonnes anonymes du CIF
NOMS_CIF = {"column0": "id_cif", "column1": "nom_ou_raison_sociale", "column2": "prenom",
            "column3": "date_naissance", "column4": "adresse", "column5": "cp", "column6": "ville",
            "column7": "pays", "column8": "telephone", "column9": "email"}

# Table → (nature, clé primaire)
CIBLES = {"crm_client":   ("client",   "client_id"),
          "crm_contrat":  ("contrat",  "contrat_id"),
          "crm_sinistre": ("sinistre", "sinistre_id"),
          "cif_clients":  ("cif",      "id_cif")}

def charger(table, nature, cle):
    df = lire(f"SELECT * FROM {BASE}.{table} WHERE _batch_id = :b", b=BATCH)
    if nature == "cif":
        df = df.rename(columns=NOMS_CIF)
    df["source_systeme"] = df["_source_system"]
    df["cle"] = df[cle]

    if nature == "contrat":
        for c in ["date_debut", "date_fin"]:
            df[c] = pd.to_datetime(df[c], errors="coerce")
        df["duree_garantie_mois"] = pd.to_numeric(df["duree_garantie_mois"], errors="coerce")
        # âge du souscripteur à la date de DÉBUT du contrat (RQ-002)
        naiss = lire(f"SELECT client_id, date_naissance FROM {BASE}.crm_client WHERE _batch_id = :b", b=BATCH)
        df = df.merge(naiss, left_on="souscripteur_id", right_on="client_id", how="left")
        dn, dd = pd.to_datetime(df["date_naissance"], errors="coerce"), df["date_debut"]
        pas_encore_anniv = (dd.dt.month < dn.dt.month) | ((dd.dt.month == dn.dt.month) & (dd.dt.day < dn.dt.day))
        df["age_debut"] = dd.dt.year - dn.dt.year - pas_encore_anniv.astype("Int64")
    return df

DONNEES = {t: (nature, charger(t, nature, cle)) for t, (nature, cle) in CIBLES.items()}
for t, (nature, d) in DONNEES.items():
    print(f"{t:<13} ({nature:<8}) : {len(d):>7} lignes")

crm_client    (client  ) :  100000 lignes
crm_contrat   (contrat ) :  100000 lignes
crm_sinistre  (sinistre) :  100000 lignes
cif_clients   (cif     ) :   40000 lignes

Cellule 5 : La fonction qui exécute une suite

In [9]:
def valider(table, df, ajouter_regles):
    nom_suite = f"{table}_suite"
    try:
        asset = datasource.get_asset(table)
    except Exception:
        asset = datasource.add_dataframe_asset(name=table)
    batch = asset.build_batch_request(dataframe=df)

    context.add_or_update_expectation_suite(expectation_suite_name=nom_suite)
    v = context.get_validator(batch_request=batch, expectation_suite_name=nom_suite)
    ajouter_regles(v)
    v.save_expectation_suite(discard_failed_expectations=False)   # → gx/expectations/<table>_suite.json
    return v.validate().results

Cellule 6 : Les règles, chacune avec son rule_id

In [10]:
SOUSCRIPTEUR_CRM = dict(row_condition='source_systeme == "crm" and type_personne == "souscripteur"', condition_parser="pandas")
FRANCE           = dict(row_condition='pays == "FR"', condition_parser="pandas")

def regles_client(v):
    # RQ-003 : téléphone du souscripteur ni nul, ni vide, ni blanc
    v.expect_column_values_to_not_be_null(column="telephone", mostly=mostly("RQ-003"), meta={"rule_id": "RQ-003"}, **SOUSCRIPTEUR_CRM)
    v.expect_column_values_to_match_regex(column="telephone", regex=r"\S", mostly=mostly("RQ-003"), meta={"rule_id": "RQ-003"}, **SOUSCRIPTEUR_CRM)
    # RQ-009 : type de personne parmi les 3 valeurs autorisées
    v.expect_column_values_to_be_in_set(column="type_personne", value_set=["prospect", "souscripteur", "assure"],
                                        meta={"rule_id": "RQ-009", "nuls_en_echec": True})

def regles_adresse(v):
    # RQ-005 : code postal à 5 chiffres, adresses en France seulement (CRM et CIF)
    v.expect_column_values_to_match_regex(column="cp", regex=r"^\d{5}$", mostly=mostly("RQ-005"),
                                          meta={"rule_id": "RQ-005", "nuls_en_echec": True}, **FRANCE)
    # RQ-007 (bonus) : pays dans la liste de référence
    v.expect_column_values_to_be_in_set(column="pays", value_set=CODES_PAYS, meta={"rule_id": "RQ-007", "nuls_en_echec": True})

def regles_contrat(v):
    # RQ-001 : date de fin strictement après la date de début
    v.expect_column_pair_values_A_to_be_greater_than_B(column_A="date_fin", column_B="date_debut", or_equal=False, meta={"rule_id": "RQ-001"})
    # RQ-002 : souscripteur de 18 ans ou plus à la date de début
    v.expect_column_values_to_be_between(column="age_debut", min_value=18, meta={"rule_id": "RQ-002"})
    # RQ-010 : durée de garantie parmi 12, 24, 36, 60
    v.expect_column_values_to_be_in_set(column="duree_garantie_mois", value_set=[12, 24, 36, 60],
                                        meta={"rule_id": "RQ-010", "nuls_en_echec": True})

def cle_primaire(v):
    # RQ-020 : clé primaire jamais nulle et unique
    v.expect_column_values_to_not_be_null(column="cle", meta={"rule_id": "RQ-020"})
    v.expect_column_values_to_be_unique(column="cle", meta={"rule_id": "RQ-020"})

SUITES = {"client":   [regles_client, regles_adresse, cle_primaire],
          "contrat":  [regles_contrat, cle_primaire],
          "sinistre": [cle_primaire],
          "cif":      [regles_adresse, cle_primaire]}

Cellule 7 : Exécuter et calculer le taux par règle

In [8]:
mesures = []
for table, (nature, df) in DONNEES.items():
    resultats = valider(table, df, lambda v: [f(v) for f in SUITES[nature]])
    par_regle = {}
    for r in resultats:
        meta = r.expectation_config.meta
        n  = r.result["element_count"]
        ko = r.result["unexpected_count"] + (r.result.get("missing_count", 0) if meta.get("nuls_en_echec") else 0)
        t0, k0 = par_regle.get(meta["rule_id"], (n, 0))
        par_regle[meta["rule_id"]] = (t0, k0 + ko)
    for rule, (n, ko) in par_regle.items():
        mesures.append({"rule_id": rule, "table": table, "testees": int(n), "echecs": int(ko)})

bilan = pd.DataFrame(mesures).sort_values(["rule_id", "table"]).reset_index(drop=True)
bilan["conformite_pct"] = (100 * (bilan.testees - bilan.echecs) / bilan.testees).round(3)
bilan["seuil_pct"] = [float(REGLES.loc[r, "seuil_min"]) for r in bilan.rule_id]
bilan["severite"]  = [REGLES.loc[r, "severite"] for r in bilan.rule_id]
bilan["verdict"]   = ["conforme" if c >= s else "sous le seuil" for c, s in zip(bilan.conformite_pct, bilan.seuil_pct)]
bilan

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/36 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/7 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/23 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/9 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/22 [00:00<?, ?it/s]

,rule_id,table,testees,echecs,conformite_pct,seuil_pct,severite,verdict
0,RQ-001,crm_contrat,100000,800,99.200,100.0,BLOQUANTE,sous le seuil
1,RQ-002,crm_contrat,100000,301,99.699,100.0,BLOQUANTE,sous le seuil
2,RQ-003,crm_client,49898,5989,87.998,98.0,AVERTISSEMENT,sous le seuil
3,RQ-005,cif_clients,39401,0,100.000,98.0,AVERTISSEMENT,conforme
4,RQ-005,crm_client,95437,1456,98.474,98.0,AVERTISSEMENT,conforme
5,RQ-007,cif_clients,40000,0,100.000,100.0,BLOQUANTE,conforme
6,RQ-007,crm_client,100000,3050,96.950,100.0,BLOQUANTE,sous le seuil
7,RQ-009,crm_client,100000,200,99.800,100.0,BLOQUANTE,sous le seuil
8,RQ-010,crm_contrat,100000,600,99.400,100.0,BLOQUANTE,sous le seuil
9,RQ-020,cif_clients,40000,0,100.000,100.0,BLOQUANTE,conforme
10,RQ-020,crm_client,100000,0,100.000,100.0,BLOQUANTE,conforme
11,RQ-020,crm_contrat,100000,0,100.000,100.0,BLOQUANTE,conforme
12,RQ-020,crm_sinistre,100000,0,100.000,100.0,BLOQUANTE,conforme

In [16]:
TYPES = {
    "RQ-001": "column_pair_values_A_to_be_greater_than_B (date_fin > date_debut)",
    "RQ-002": "column_values_to_be_between (age_debut ≥ 18)",
    "RQ-003": "column_values_to_not_be_null + match_regex \\S (souscripteurs)",
    "RQ-005": "column_values_to_match_regex ^\\d{5}$ (adresses FR)",
    "RQ-007": "column_values_to_be_in_set (silver.ref_pays)",
    "RQ-009": "column_values_to_be_in_set (prospect, souscripteur, assure)",
    "RQ-010": "column_values_to_be_in_set (12, 24, 36, 60)",
    "RQ-020": "column_values_to_not_be_null + to_be_unique (clé)",
}
page15 = bilan.assign(expectation=bilan.rule_id.map(TYPES))[
    ["rule_id", "table", "expectation", "testees", "echecs", "conformite_pct", "severite"]]
page15.columns = ["Règle", "Table bronze", "Expectation (type)", "Testées", "En échec", "Taux (%)", "Sévérité"]
pd.set_option("display.max_colwidth", None)
page15

,Règle,Table bronze,Expectation (type),Testées,En échec,Taux (%),Sévérité
0,RQ-001,crm_contrat,column_pair_values_A_to_be_greater_than_B (date_fin > date_debut),100000,800,99.200,BLOQUANTE
1,RQ-002,crm_contrat,column_values_to_be_between (age_debut ≥ 18),100000,301,99.699,BLOQUANTE
2,RQ-003,crm_client,column_values_to_not_be_null + match_regex \S (souscripteurs),49898,5989,87.998,AVERTISSEMENT
3,RQ-005,cif_clients,column_values_to_match_regex ^\d{5}$ (adresses FR),39401,0,100.000,AVERTISSEMENT
4,RQ-005,crm_client,column_values_to_match_regex ^\d{5}$ (adresses FR),95437,1456,98.474,AVERTISSEMENT
5,RQ-007,cif_clients,column_values_to_be_in_set (silver.ref_pays),40000,0,100.000,BLOQUANTE
6,RQ-007,crm_client,column_values_to_be_in_set (silver.ref_pays),100000,3050,96.950,BLOQUANTE
7,RQ-009,crm_client,"column_values_to_be_in_set (prospect, souscripteur, assure)",100000,200,99.800,BLOQUANTE
8,RQ-010,crm_contrat,"column_values_to_be_in_set (12, 24, 36, 60)",100000,600,99.400,BLOQUANTE
9,RQ-020,cif_clients,column_values_to_not_be_null + to_be_unique (clé),40000,0,100.000,BLOQUANTE
10,RQ-020,crm_client,column_values_to_not_be_null + to_be_unique (clé),100000,0,100.000,BLOQUANTE
11,RQ-020,crm_contrat,column_values_to_not_be_null + to_be_unique (clé),100000,0,100.000,BLOQUANTE
12,RQ-020,crm_sinistre,column_values_to_not_be_null + to_be_unique (clé),100000,0,100.000,BLOQUANTE

Cellule 9 : Les pièges, avant / après

In [11]:
cl  = DONNEES["crm_client"][1]
cif = DONNEES["cif_clients"][1]
sous = cl[(cl.source_systeme == "crm") & (cl.type_personne == "souscripteur")]

# Piège 1 — RQ-003 : nul, vide et blanc sont trois cas différents
avant_rq003 = int(sous.telephone.isna().sum())
apres_rq003 = int((sous.telephone.isna() | (sous.telephone.fillna("x").str.strip() == "")).sum())

# Piège 2 — RQ-005 : sans filtre « France », les CP étrangers comptent comme erreurs
avant_crm = int((~cl.cp.fillna("").str.fullmatch(r"\d{5}")).sum())
apres_crm = int((~cl[cl.pays == "FR"].cp.fillna("").str.fullmatch(r"\d{5}")).sum())
avant_cif = int((~cif.cp.fillna("").str.fullmatch(r"\d{5}")).sum())
apres_cif = int((~cif[cif.pays == "FR"].cp.fillna("").str.fullmatch(r"\d{5}")).sum())

# Piège 3 — RQ-009 : la comparaison est exacte (casse comprise)
domaine = ["prospect", "souscripteur", "assure"]
avant_rq009 = int((~cl.type_personne.str.lower().isin(domaine)).sum())   # insensible à la casse
apres_rq009 = int((~cl.type_personne.isin(domaine)).sum())               # exacte

pieges = pd.DataFrame([
    ["RQ-003", "nul, vide et blanc : tester seulement NULL",    avant_rq003, apres_rq003],
    ["RQ-005", "adresses étrangères (CRM) : filtre pays = FR",  avant_crm,   apres_crm],
    ["RQ-005", "adresses étrangères (CIF) : filtre pays = FR",  avant_cif,   apres_cif],
    ["RQ-009", "comparaison exacte (casse) vs insensible",      avant_rq009, apres_rq009],
], columns=["Règle", "Piège", "Avant correction", "Après correction"])
pieges

,Règle,Piège,Avant correction,Après correction
0,RQ-003,"nul, vide et blanc : tester seulement NULL",1995,5989
1,RQ-005,adresses étrangères (CRM) : filtre pays = FR,2317,1456
2,RQ-005,adresses étrangères (CIF) : filtre pays = FR,341,0
3,RQ-009,comparaison exacte (casse) vs insensible,120,200

# **US-11**

In [12]:
# US-11 — vérifier les résultats disponibles
display(bilan)
print("\nTables chargées :", list(DONNEES.keys()))

for table, (nature, df) in DONNEES.items():
    print(f"{table}: {len(df)} lignes")

,rule_id,table,testees,echecs,conformite_pct,seuil_pct,severite,verdict
0,RQ-001,crm_contrat,100000,800,99.200,100.0,BLOQUANTE,sous le seuil
1,RQ-002,crm_contrat,100000,301,99.699,100.0,BLOQUANTE,sous le seuil
2,RQ-003,crm_client,49898,5989,87.998,98.0,AVERTISSEMENT,sous le seuil
3,RQ-005,cif_clients,39401,0,100.000,98.0,AVERTISSEMENT,conforme
4,RQ-005,crm_client,95437,1456,98.474,98.0,AVERTISSEMENT,conforme
5,RQ-007,cif_clients,40000,0,100.000,100.0,BLOQUANTE,conforme
6,RQ-007,crm_client,100000,3050,96.950,100.0,BLOQUANTE,sous le seuil
7,RQ-009,crm_client,100000,200,99.800,100.0,BLOQUANTE,sous le seuil
8,RQ-010,crm_contrat,100000,600,99.400,100.0,BLOQUANTE,sous le seuil
9,RQ-020,cif_clients,40000,0,100.000,100.0,BLOQUANTE,conforme
10,RQ-020,crm_client,100000,0,100.000,100.0,BLOQUANTE,conforme
11,RQ-020,crm_contrat,100000,0,100.000,100.0,BLOQUANTE,conforme
12,RQ-020,crm_sinistre,100000,0,100.000,100.0,BLOQUANTE,conforme

Tables chargées : ['crm_client', 'crm_contrat', 'crm_sinistre', 'cif_clients']
crm_client: 100000 lignes
crm_contrat: 100000 lignes
crm_sinistre: 100000 lignes
cif_clients: 40000 lignes

In [13]:
for table, (_, df) in DONNEES.items():
    print(f"\n--- {table} ---")
    print(df.columns.tolist())
    display(df.head(2))

--- crm_client ---
['bronze_row_id', 'client_id', 'type_personne', 'nom', 'prenom', 'raison_sociale', 'date_naissance', 'adresse', 'cp', 'ville', 'pays', 'telephone', 'email', 'date_creation', '_batch_id', '_source_system', '_ingested_at', '_row_hash', 'source_systeme', 'cle']

,bronze_row_id,client_id,type_personne,nom,prenom,raison_sociale,date_naissance,adresse,cp,ville,pays,telephone,email,date_creation,_batch_id,_source_system,_ingested_at,_row_hash,source_systeme,cle
0,100001,A-1000,souscripteur,Thomas,Sandrine,None,1975-04-16,31 rue Anatole France,69300,Caluire-et-Cuire,FR,0346234195,sandrine.thomas1093@free.fr,2019-12-25,L-2026-10-01,crm,2026-10-21 11:38:58,8fe9e59d3f5268ea,crm,A-1000
1,100002,A-10000,assure,Leroy,Karim,None,1942-03-02,81 rue du Moulin,73000,Chambéry,FR,0212942708,contact@batimentgiraudsa6308.fr,2018-06-30,L-2026-10-01,crm,2026-10-21 11:38:58,bf96f99ffb10ed08,crm,A-10000

--- crm_contrat ---
['bronze_row_id', 'contrat_id', 'souscripteur_id', 'assure_id', 'code_type', 'date_debut', 'date_fin', 'duree_garantie_mois', 'prime_annuelle', 'date_derniere_cotisation', '_batch_id', '_source_system', '_ingested_at', '_row_hash', 'source_systeme', 'cle', 'client_id', 'date_naissance', 'age_debut']

,bronze_row_id,contrat_id,souscripteur_id,assure_id,code_type,date_debut,date_fin,duree_garantie_mois,prime_annuelle,date_derniere_cotisation,_batch_id,_source_system,_ingested_at,_row_hash,source_systeme,cle,client_id,date_naissance,age_debut
0,1,CT0000001,A-18356,0,T02,2009-08-10,2019-08-09,120,615.15,2019-07-15,L-2026-10-01,crm,2026-10-21 11:38:15,9a4fe6880c9916f9,crm,CT0000001,A-18356,1946-01-12,63.0
1,2,CT0000002,H-22766,H-28231,T07,2009-08-22,2019-08-21,120,237.93,2019-08-10,L-2026-10-01,crm,2026-10-21 11:38:15,98ac682db6191c3c,crm,CT0000002,H-22766,1954-04-01,55.0

--- crm_sinistre ---
['bronze_row_id', 'sinistre_id', 'contrat_id', 'date_survenance', 'date_declaration', 'type_sinistre', 'montant_estime', 'adresse_sinistre', 'cp_sinistre', 'ville_sinistre', 'canal_saisie', '_batch_id', '_source_system', '_ingested_at', '_row_hash', 'source_systeme', 'cle']

,bronze_row_id,sinistre_id,contrat_id,date_survenance,date_declaration,type_sinistre,montant_estime,adresse_sinistre,cp_sinistre,ville_sinistre,canal_saisie,_batch_id,_source_system,_ingested_at,_row_hash,source_systeme,cle
0,1,SIN0000001,CT0000002,2012-04-16,2012-04-27,événement climatique,1163.63,1 rue du Commercce,03400,Yzeure,ressaisie_manuelle,L-2026-10-01,crm,2026-10-21 11:38:28,38ad9da538eff047,crm,SIN0000001
1,2,SIN0000002,CT0000003,2012-06-01,2012-06-22,dégât des eaux,2922.64,62 rue Nationale,20000,Ajaccio,import_expert,L-2026-10-01,crm,2026-10-21 11:38:28,3f4d77170c278631,crm,SIN0000002

--- cif_clients ---
['bronze_row_id', 'id_cif', 'nom_ou_raison_sociale', 'prenom', 'date_naissance', 'adresse', 'cp', 'ville', 'pays', 'telephone', 'email', '_batch_id', '_source_system', '_ingested_at', '_row_hash', 'source_systeme', 'cle']

,bronze_row_id,id_cif,nom_ou_raison_sociale,prenom,date_naissance,adresse,cp,ville,pays,telephone,email,_batch_id,_source_system,_ingested_at,_row_hash,source_systeme,cle
0,1,K100040,LECLERCQ,Bernard,12/07/1963,49 rue Hoche,74100,ANNEMASSE,FR,0101389234,bernard.leclercq1957@orange.fr,L-2026-10-01,cif,2026-10-21 11:38:36,fe1d3d2030ff65ef,cif,K100040
1,2,K100056,DAVID,Romain,26/01/1970,58 AVENUE DU GÉNÉRAL DE GAULLE,07200,AUBENAS,FR,0455645409,romain.david4526@gmail.com,L-2026-10-01,cif,2026-10-21 11:38:36,cac38aa00ab09b7e,cif,K100056

In [14]:
# US-11 — Extraction des lignes en échec
import pandas as pd
from pathlib import Path

echecs = []

def ajouter_echecs(rule_id, table, df, masque, famille, action):
    lignes = df.loc[masque.fillna(False)].copy()
    if lignes.empty:
        return

    lignes["rule_id"] = rule_id
    lignes["table_source"] = table
    lignes["famille_erreur"] = famille
    lignes["cause_probable"] = famille
    lignes["action_proposee"] = action
    echecs.append(lignes)


# RQ-001 — date de fin antérieure ou égale à la date de début
contrats = DONNEES["crm_contrat"][1]

debut = pd.to_datetime(contrats["date_debut"], errors="coerce")
fin = pd.to_datetime(contrats["date_fin"], errors="coerce")

ajouter_echecs(
    "RQ-001", "crm_contrat", contrats,
    debut.notna() & fin.notna() & (fin <= debut),
    "Date de fin non postérieure à la date de début",
    "Vérifier les dates du contrat auprès de l'équipe métier"
)


# RQ-002 — âge inférieur à 18 ans à la date de début
age = pd.to_numeric(contrats["age_debut"], errors="coerce")

ajouter_echecs(
    "RQ-002", "crm_contrat", contrats,
    age.notna() & (age < 18),
    "Âge du souscripteur inférieur à 18 ans",
    "Vérifier la date de naissance et la date de début du contrat"
)


# RQ-003 — téléphone nul, vide ou composé d'espaces
clients = DONNEES["crm_client"][1]
souscripteurs = clients[
    clients["type_personne"].astype(str).str.lower() == "souscripteur"
]

telephone = souscripteurs["telephone"].fillna("").astype(str).str.strip()

ajouter_echecs(
    "RQ-003", "crm_client", souscripteurs,
    telephone.eq(""),
    "Téléphone nul, vide ou blanc",
    "Demander à l'équipe CRM de vérifier le téléphone"
)


# RQ-005 — code postal français invalide
for table in ["crm_client", "cif_clients"]:
    df = DONNEES[table][1]
    cp = df["cp"].fillna("").astype(str).str.strip()

    masque = (
        df["pays"].astype(str).str.strip().eq("FR")
        & ~cp.str.fullmatch(r"\d{5}", na=False)
    )

    ajouter_echecs(
        "RQ-005", table, df, masque,
        "Code postal français différent de cinq chiffres",
        "Vérifier et corriger le code postal si nécessaire"
    )


# RQ-009 — type de personne non autorisé
types_valides = {"prospect", "souscripteur", "assure"}

type_personne = clients["type_personne"].astype(str)

ajouter_echecs(
    "RQ-009", "crm_client", clients,
    ~type_personne.isin(types_valides),
    "Type de personne non autorisé",
    "Vérifier la valeur dans le référentiel des types de personne"
)


# RQ-010 — durée de garantie non autorisée
duree = pd.to_numeric(contrats["duree_garantie_mois"], errors="coerce")

ajouter_echecs(
    "RQ-010", "crm_contrat", contrats,
    ~duree.isin([12, 24, 36, 60]),
    "Durée de garantie hors des valeurs autorisées",
    "Vérifier la durée auprès de l'équipe contrats"
)


# Consolider et exporter
export_echecs = (
    pd.concat(echecs, ignore_index=True)
    if echecs
    else pd.DataFrame()
)

dossier = Path("reports/ge")
dossier.mkdir(parents=True, exist_ok=True)

fichier_complet = dossier / "us11_lignes_en_echec.csv"
fichier_20 = dossier / "us11_echantillon_20_lignes.csv"

export_echecs.to_csv(fichier_complet, index=False, encoding="utf-8-sig")

echantillon_20 = export_echecs.head(20).copy()
echantillon_20.to_csv(fichier_20, index=False, encoding="utf-8-sig")

print("Total des lignes extraites :", len(export_echecs))
print("Export complet :", fichier_complet)
print("Échantillon :", fichier_20)

display(
    export_echecs.groupby(["rule_id", "table_source"])
    .size()
    .reset_index(name="lignes_extraites")
)

display(echantillon_20)

Total des lignes extraites : 9352
Export complet : reports/ge/us11_lignes_en_echec.csv
Échantillon : reports/ge/us11_echantillon_20_lignes.csv

  rule_id table_source  lignes_extraites
0  RQ-001  crm_contrat               800
1  RQ-002  crm_contrat               301
2  RQ-003   crm_client              5995
3  RQ-005   crm_client              1456
4  RQ-009   crm_client               200
5  RQ-010  crm_contrat               600

,bronze_row_id,contrat_id,souscripteur_id,assure_id,code_type,date_debut,date_fin,duree_garantie_mois,prime_annuelle,date_derniere_cotisation,...,nom,prenom,raison_sociale,adresse,cp,ville,pays,telephone,email,date_creation
0,44,CT0000044,H-26157,S-24675,T07,2014-02-03,2014-02-03,60.0,264.74,2019-01-16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,106,CT0000106,H-27702,0,T08,2014-03-11,2014-03-11,60.0,948.52,2019-02-08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,147,CT0000147,H-29684,A-32625,T05,2014-04-05,2014-03-08,60.0,408.28,2019-03-12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,158,CT0000158,A-17235,A-2559,T03,2014-04-16,2014-04-16,60.0,414.72,2019-04-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,210,CT0000210,H-26425,S-23715,T07,2014-05-19,2014-05-19,60.0,250.54,2019-04-28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,244,CT0000244,S-19554,S-23488,T11,2014-06-07,2014-06-07,60.0,931.64,2019-05-20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,260,CT0000260,S-16390,H-20964,T11,2014-06-16,2014-05-28,60.0,1070.21,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,284,CT0000284,S-23320,A-22785,T10,2014-06-27,2014-06-20,60.0,2104.67,2019-05-27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,349,CT0000349,H-24398,A-16521,T07,2014-08-12,2014-08-12,60.0,370.12,2019-08-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,368,CT0000368,A-7001,S-12858,T01,2014-08-21,2014-08-21,60.0,772.21,2019-07-13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,376,CT0000376,S-18475,A-8989,T12,2014-08-25,2014-07-27,60.0,580.07,2019-07-27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,384,CT0000384,S-1105,S-12920,T11,2014-08-30,2014-08-04,60.0,1818.61,2019-08-28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,385,CT0000385,H-20294,0,T05,2014-08-31,2014-08-02,60.0,395.63,2019-08-24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,527,CT0000527,H-6772,S-12593,T08,2014-11-20,2014-11-03,60.0,454.91,2019-11-12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,534,CT0000534,A-21347,H-13880,T04,2014-11-23,2014-11-13,60.0,1076.77,2019-11-02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,535,CT0000535,H-7191,S-6300,T06,2014-11-23,2014-11-23,60.0,131.36,2019-11-21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,572,CT0000572,H-23045,A-8349,T08,2014-12-15,2014-12-15,60.0,995.48,2019-12-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,574,CT0000574,A-11205,H-5486,T03,2014-12-17,2014-12-17,60.0,539.56,2019-10-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,605,CT0000605,A-21401,S-14963,T02,2015-01-11,2015-01-06,60.0,399.68,2019-12-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,617,CT0000617,H-20976,S-4526,T08,2015-01-19,2015-01-04,60.0,936.43,2019-11-25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
clients = DONNEES["crm_client"][1]

souscripteurs = clients[
    clients["type_personne"]
    .astype("string")
    .str.strip()
    .str.lower()
    .eq("souscripteur")
]

print("Nombre de souscripteurs :", len(souscripteurs))
print(
    "Téléphone vide ou absent :",
    souscripteurs["telephone"].isna().sum()
    + souscripteurs["telephone"].fillna("").str.strip().eq("").sum()
    - (
        souscripteurs["telephone"].isna()
        & souscripteurs["telephone"].fillna("").str.strip().eq("")
    ).sum()
)

Nombre de souscripteurs : 49978
Téléphone vide ou absent : 5995

In [16]:
clients = DONNEES["crm_client"][1]

type_sans_strip = (
    clients["type_personne"].astype(str).str.lower()
)
type_avec_strip = type_sans_strip.str.strip()

print("Sans strip :", type_sans_strip.eq("souscripteur").sum())
print("Avec strip :", type_avec_strip.eq("souscripteur").sum())

souscripteurs = clients[type_avec_strip.eq("souscripteur")]
telephone = souscripteurs["telephone"].fillna("").astype(str).str.strip()

print("Échecs téléphone :", telephone.eq("").sum())

Sans strip : 49978
Avec strip : 49978
Échecs téléphone : 5995

In [17]:
# Vérification de RQ-003
clients = DONNEES["crm_client"][1]

print("Nombre total de clients :", len(clients))
print("\nValeurs de type_personne :")
print(clients["type_personne"].value_counts(dropna=False))

print("\nNombre de téléphones absents :")
print(clients["telephone"].isna().sum())

print("\nNombre de téléphones vides ou blancs :")
telephone = clients["telephone"].fillna("").astype(str).str.strip()
print(telephone.eq("").sum())

Nombre total de clients : 100000

Valeurs de type_personne :
type_personne
souscripteur    49898
assure          28944
prospect        20958
client             60
Souscripteur       50
assuré             40
SOUSCRIPTEUR       30
prosp.             20
Name: count, dtype: int64

Nombre de téléphones absents :
5999

Nombre de téléphones vides ou blancs :
9999

In [18]:
# RQ-003 — Vérification exacte
clients = DONNEES["crm_client"][1]

souscripteurs = clients[
    clients["type_personne"].astype(str).str.lower().eq("souscripteur")
]

telephone = souscripteurs["telephone"].fillna("").astype(str).str.strip()

print("Souscripteurs testés :", len(souscripteurs))
print("Téléphones en échec :", telephone.eq("").sum())
print("Téléphones renseignés :", telephone.ne("").sum())

Souscripteurs testés : 49978
Téléphones en échec : 5995
Téléphones renseignés : 43983

In [26]:

# US-11 — Extraction et export des lignes en échec

import pandas as pd
from pathlib import Path

echecs = []

def ajouter_echecs(rule_id, table, df, masque, famille, action):
    lignes = df.loc[masque.fillna(False)].copy()

    if lignes.empty:
        return

    lignes["rule_id"] = rule_id
    lignes["table_source"] = table
    lignes["famille_erreur"] = famille
    lignes["cause_probable"] = famille
    lignes["action_proposee"] = action

    echecs.append(lignes)


# RQ-001 — Date de fin antérieure ou égale à la date de début
contrats = DONNEES["crm_contrat"][1]

debut = pd.to_datetime(contrats["date_debut"], errors="coerce")
fin = pd.to_datetime(contrats["date_fin"], errors="coerce")

ajouter_echecs(
    "RQ-001", "crm_contrat", contrats,
    debut.notna() & fin.notna() & (fin <= debut),
    "Dates de contrat incohérentes",
    "Vérifier les dates de début et de fin du contrat"
)


# RQ-002 — Âge au début du contrat inférieur à 18 ans
contrats = DONNEES["crm_contrat"][1]
age = pd.to_numeric(contrats["age_debut"], errors="coerce")

ajouter_echecs(
    "RQ-002", "crm_contrat", contrats,
    age.lt(18),
    "Âge inférieur à 18 ans",
    "Vérifier la date de naissance et les conditions du contrat"
)


# RQ-003 — Téléphone nul, vide ou composé d'espaces
clients = DONNEES["crm_client"][1]

souscripteurs = clients[
    clients["type_personne"].astype(str) == "souscripteur"
]

telephone = (
    souscripteurs["telephone"]
    .fillna("")
    .astype(str)
    .str.strip()
)

ajouter_echecs(
    "RQ-003", "crm_client", souscripteurs,
    telephone.eq(""),
    "Téléphone nul, vide ou blanc",
    "Demander à l'équipe CRM de vérifier le téléphone"
)


# RQ-005 — Code postal français invalide
for table in ["crm_client", "cif_clients"]:
    df = DONNEES[table][1]

    pays = df["pays"].fillna("").astype(str).str.strip().str.upper()
    cp = df["cp"].fillna("").astype(str).str.strip()

    masque = pays.eq("FR") & ~cp.str.fullmatch(r"\d{5}", na=False)

    ajouter_echecs(
        "RQ-005", table, df, masque,
        "Code postal français invalide",
        "Vérifier et corriger le code postal dans la source"
    )


# RQ-009 — Type de personne non reconnu
clients = DONNEES["crm_client"][1]

types_valides = {"prospect", "souscripteur", "assure"}
type_personne = (
    clients["type_personne"]
    .fillna("")
    .astype(str)
    .str.strip()
    .str.lower()
)

ajouter_echecs(
    "RQ-009", "crm_client", clients,
    ~type_personne.isin(types_valides),
    "Type de personne non reconnu",
    "Normaliser le type de personne dans le référentiel CRM"
)


# RQ-010 — Durée de garantie non autorisée
contrats = DONNEES["crm_contrat"][1]

duree = pd.to_numeric(
    contrats["duree_garantie_mois"], errors="coerce"
)

durees_valides = {12, 24, 36, 60}

ajouter_echecs(
    "RQ-010", "crm_contrat", contrats,
    ~duree.isin(durees_valides),
    "Durée de garantie non autorisée",
    "Vérifier la durée de garantie et le type de contrat"
)


# RQ-020 — Clés primaires absentes ou dupliquées

cles_principales = {
    "crm_client": "client_id",
    "crm_contrat": "contrat_id",
    "crm_sinistre": "sinistre_id",
    "cif_clients": "id_cif"
}

for table, colonne in cles_principales.items():
    df = DONNEES[table][1]

    absentes = df[colonne].isna() | df[colonne].astype(str).str.strip().eq("")
    dupliquees = df[colonne].notna() & df[colonne].duplicated(keep=False)

    masque = absentes | dupliquees

    ajouter_echecs(
        "RQ-020", table, df, masque,
        "Clé primaire absente ou dupliquée",
        "Corriger la clé dans le système source"
    )

print("Contrôle RQ-020 terminé.")



# Regroupement des échecs
if echecs:
    export_echecs = pd.concat(echecs, ignore_index=True)
else:
    export_echecs = pd.DataFrame()

# Création du dossier de sortie
dossier = Path("reports/ge")
dossier.mkdir(parents=True, exist_ok=True)

# Export complet
fichier_complet = dossier / "us11_lignes_en_echec.csv"
export_echecs.to_csv(fichier_complet, index=False, encoding="utf-8-sig")

# Échantillon de 20 lignes, si disponible
echantillon = export_echecs.head(20).copy()
fichier_echantillon = dossier / "us11_echantillon_20_lignes.csv"
echantillon.to_csv(fichier_echantillon, index=False, encoding="utf-8-sig")

# Résultats
print("Total des lignes extraites :", len(export_echecs))
print("\nNombre de lignes par règle :")

if not export_echecs.empty:
    print(
        export_echecs.groupby(["rule_id", "table_source"])
        .size()
        .reset_index(name="lignes_extraites")
        .to_string(index=False)
    )

print("\nExport complet :", fichier_complet)
print("Échantillon :", fichier_echantillon)

display(echantillon)

Contrôle RQ-020 terminé.
Total des lignes extraites : 9268

Nombre de lignes par règle :
rule_id table_source  lignes_extraites
 RQ-001  crm_contrat               800
 RQ-002  crm_contrat               301
 RQ-003   crm_client              5989
 RQ-005   crm_client              1458
 RQ-009   crm_client               120
 RQ-010  crm_contrat               600

Export complet : reports/ge/us11_lignes_en_echec.csv
Échantillon : reports/ge/us11_echantillon_20_lignes.csv

,bronze_row_id,contrat_id,souscripteur_id,assure_id,code_type,date_debut,date_fin,duree_garantie_mois,prime_annuelle,date_derniere_cotisation,...,nom,prenom,raison_sociale,adresse,cp,ville,pays,telephone,email,date_creation
0,44,CT0000044,H-26157,S-24675,T07,2014-02-03,2014-02-03,60.0,264.74,2019-01-16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,106,CT0000106,H-27702,0,T08,2014-03-11,2014-03-11,60.0,948.52,2019-02-08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,147,CT0000147,H-29684,A-32625,T05,2014-04-05,2014-03-08,60.0,408.28,2019-03-12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,158,CT0000158,A-17235,A-2559,T03,2014-04-16,2014-04-16,60.0,414.72,2019-04-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,210,CT0000210,H-26425,S-23715,T07,2014-05-19,2014-05-19,60.0,250.54,2019-04-28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,244,CT0000244,S-19554,S-23488,T11,2014-06-07,2014-06-07,60.0,931.64,2019-05-20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,260,CT0000260,S-16390,H-20964,T11,2014-06-16,2014-05-28,60.0,1070.21,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,284,CT0000284,S-23320,A-22785,T10,2014-06-27,2014-06-20,60.0,2104.67,2019-05-27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,349,CT0000349,H-24398,A-16521,T07,2014-08-12,2014-08-12,60.0,370.12,2019-08-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,368,CT0000368,A-7001,S-12858,T01,2014-08-21,2014-08-21,60.0,772.21,2019-07-13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,376,CT0000376,S-18475,A-8989,T12,2014-08-25,2014-07-27,60.0,580.07,2019-07-27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,384,CT0000384,S-1105,S-12920,T11,2014-08-30,2014-08-04,60.0,1818.61,2019-08-28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,385,CT0000385,H-20294,0,T05,2014-08-31,2014-08-02,60.0,395.63,2019-08-24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,527,CT0000527,H-6772,S-12593,T08,2014-11-20,2014-11-03,60.0,454.91,2019-11-12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,534,CT0000534,A-21347,H-13880,T04,2014-11-23,2014-11-13,60.0,1076.77,2019-11-02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,535,CT0000535,H-7191,S-6300,T06,2014-11-23,2014-11-23,60.0,131.36,2019-11-21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,572,CT0000572,H-23045,A-8349,T08,2014-12-15,2014-12-15,60.0,995.48,2019-12-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,574,CT0000574,A-11205,H-5486,T03,2014-12-17,2014-12-17,60.0,539.56,2019-10-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,605,CT0000605,A-21401,S-14963,T02,2015-01-11,2015-01-06,60.0,399.68,2019-12-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,617,CT0000617,H-20976,S-4526,T08,2015-01-19,2015-01-04,60.0,936.43,2019-11-25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
# US-11 — Vérification des clés disponibles

for table in ["crm_client", "crm_contrat", "crm_sinistre", "cif_clients"]:
    df = DONNEES[table][1]

    print(f"\n--- {table} ---")
    print("Colonnes candidates :", [
        c for c in df.columns
        if c.endswith("_id") or c == "cle"
    ])

--- crm_client ---
Colonnes candidates : ['bronze_row_id', 'client_id', '_batch_id', 'cle']

--- crm_contrat ---
Colonnes candidates : ['bronze_row_id', 'contrat_id', 'souscripteur_id', 'assure_id', '_batch_id', 'cle', 'client_id']

--- crm_sinistre ---
Colonnes candidates : ['bronze_row_id', 'sinistre_id', 'contrat_id', '_batch_id', 'cle']

--- cif_clients ---
Colonnes candidates : ['bronze_row_id', '_batch_id', 'cle']

In [23]:

# US-11 — Diagnostic des clés pour RQ-020

for table in ["crm_client", "crm_contrat", "crm_sinistre", "cif_clients"]:
    df = DONNEES[table][1]

    print(f"\n--- {table} ---")

    for colonne in ["client_id", "contrat_id", "sinistre_id", "id_cif", "cle"]:
        if colonne in df.columns:
            valeurs = df[colonne]
            print(
                f"{colonne} : "
                f"{valeurs.isna().sum()} valeurs absentes ; "
                f"{valeurs.duplicated().sum()} doublons "
                f"(dont éventuelles valeurs absentes)"
            )

--- crm_client ---
client_id : 0 valeurs absentes ; 0 doublons (dont éventuelles valeurs absentes)
cle : 0 valeurs absentes ; 0 doublons (dont éventuelles valeurs absentes)

--- crm_contrat ---
client_id : 1000 valeurs absentes ; 50478 doublons (dont éventuelles valeurs absentes)
contrat_id : 0 valeurs absentes ; 0 doublons (dont éventuelles valeurs absentes)
cle : 0 valeurs absentes ; 0 doublons (dont éventuelles valeurs absentes)

--- crm_sinistre ---
contrat_id : 0 valeurs absentes ; 37218 doublons (dont éventuelles valeurs absentes)
sinistre_id : 0 valeurs absentes ; 0 doublons (dont éventuelles valeurs absentes)
cle : 0 valeurs absentes ; 0 doublons (dont éventuelles valeurs absentes)

--- cif_clients ---
id_cif : 0 valeurs absentes ; 0 doublons (dont éventuelles valeurs absentes)
cle : 0 valeurs absentes ; 0 doublons (dont éventuelles valeurs absentes)

In [24]:
# US-11 — RQ-020 : contrôle des clés techniques

cles_principales = {
    "crm_client": "client_id",
    "crm_contrat": "contrat_id",
    "crm_sinistre": "sinistre_id",
    "cif_clients": "id_cif"
}

for table, colonne in cles_principales.items():
    df = DONNEES[table][1]

    masque = df[colonne].isna() | (
        df[colonne].astype(str).str.strip().eq("")
    )

    doublons = df[colonne].notna() & df[colonne].duplicated(keep=False)

    print(
        f"{table} — {colonne} : "
        f"{masque.sum()} clés absentes, "
        f"{doublons.sum()} lignes avec clé dupliquée"
    )

crm_client — client_id : 0 clés absentes, 0 lignes avec clé dupliquée
crm_contrat — contrat_id : 0 clés absentes, 0 lignes avec clé dupliquée
crm_sinistre — sinistre_id : 0 clés absentes, 0 lignes avec clé dupliquée
cif_clients — id_cif : 0 clés absentes, 0 lignes avec clé dupliquée

In [27]:

# US-11 — Échantillon de 20 lignes commentées

# On utilise les lignes déjà extraites
echantillon = export_echecs.head(20).copy()

# Explication et action corrective pour chaque ligne
echantillon["commentaire"] = (
    "Échec de la règle "
    + echantillon["rule_id"].astype(str)
    + " : "
    + echantillon["cause_probable"].astype(str)
)

echantillon["action_corrective"] = echantillon["action_proposee"]

# Colonnes utiles pour le livrable
colonnes = [
    "rule_id",
    "table_source",
    "bronze_row_id",
    "cause_probable",
    "commentaire",
    "action_corrective"
]

colonnes = [c for c in colonnes if c in echantillon.columns]
echantillon_final = echantillon[colonnes]

# Export
from pathlib import Path

dossier = Path("reports/ge")
dossier.mkdir(parents=True, exist_ok=True)

fichier = dossier / "us11_echantillon_20_lignes_commentees.csv"
echantillon_final.to_csv(fichier, index=False, encoding="utf-8-sig")

print("Nombre de lignes commentées :", len(echantillon_final))
print("Fichier créé :", fichier)

display(echantillon_final)

Nombre de lignes commentées : 20
Fichier créé : reports/ge/us11_echantillon_20_lignes_commentees.csv

,rule_id,table_source,bronze_row_id,cause_probable,commentaire,action_corrective
0,RQ-001,crm_contrat,44,Dates de contrat incohérentes,Échec de la règle RQ-001 : Dates de contrat in...,Vérifier les dates de début et de fin du contrat
1,RQ-001,crm_contrat,106,Dates de contrat incohérentes,Échec de la règle RQ-001 : Dates de contrat in...,Vérifier les dates de début et de fin du contrat
2,RQ-001,crm_contrat,147,Dates de contrat incohérentes,Échec de la règle RQ-001 : Dates de contrat in...,Vérifier les dates de début et de fin du contrat
3,RQ-001,crm_contrat,158,Dates de contrat incohérentes,Échec de la règle RQ-001 : Dates de contrat in...,Vérifier les dates de début et de fin du contrat
4,RQ-001,crm_contrat,210,Dates de contrat incohérentes,Échec de la règle RQ-001 : Dates de contrat in...,Vérifier les dates de début et de fin du contrat
5,RQ-001,crm_contrat,244,Dates de contrat incohérentes,Échec de la règle RQ-001 : Dates de contrat in...,Vérifier les dates de début et de fin du contrat
6,RQ-001,crm_contrat,260,Dates de contrat incohérentes,Échec de la règle RQ-001 : Dates de contrat in...,Vérifier les dates de début et de fin du contrat
7,RQ-001,crm_contrat,284,Dates de contrat incohérentes,Échec de la règle RQ-001 : Dates de contrat in...,Vérifier les dates de début et de fin du contrat
8,RQ-001,crm_contrat,349,Dates de contrat incohérentes,Échec de la règle RQ-001 : Dates de contrat in...,Vérifier les dates de début et de fin du contrat
9,RQ-001,crm_contrat,368,Dates de contrat incohérentes,Échec de la règle RQ-001 : Dates de contrat in...,Vérifier les dates de début et de fin du contrat
10,RQ-001,crm_contrat,376,Dates de contrat incohérentes,Échec de la règle RQ-001 : Dates de contrat in...,Vérifier les dates de début et de fin du contrat
11,RQ-001,crm_contrat,384,Dates de contrat incohérentes,Échec de la règle RQ-001 : Dates de contrat in...,Vérifier les dates de début et de fin du contrat
12,RQ-001,crm_contrat,385,Dates de contrat incohérentes,Échec de la règle RQ-001 : Dates de contrat in...,Vérifier les dates de début et de fin du contrat
13,RQ-001,crm_contrat,527,Dates de contrat incohérentes,Échec de la règle RQ-001 : Dates de contrat in...,Vérifier les dates de début et de fin du contrat
14,RQ-001,crm_contrat,534,Dates de contrat incohérentes,Échec de la règle RQ-001 : Dates de contrat in...,Vérifier les dates de début et de fin du contrat
15,RQ-001,crm_contrat,535,Dates de contrat incohérentes,Échec de la règle RQ-001 : Dates de contrat in...,Vérifier les dates de début et de fin du contrat
16,RQ-001,crm_contrat,572,Dates de contrat incohérentes,Échec de la règle RQ-001 : Dates de contrat in...,Vérifier les dates de début et de fin du contrat
17,RQ-001,crm_contrat,574,Dates de contrat incohérentes,Échec de la règle RQ-001 : Dates de contrat in...,Vérifier les dates de début et de fin du contrat
18,RQ-001,crm_contrat,605,Dates de contrat incohérentes,Échec de la règle RQ-001 : Dates de contrat in...,Vérifier les dates de début et de fin du contrat
19,RQ-001,crm_contrat,617,Dates de contrat incohérentes,Échec de la règle RQ-001 : Dates de contrat in...,Vérifier les dates de début et de fin du contrat