# **US-10**

Cellule 1 : Connexions et paramètres

In [2]:
import os
import pandas as pd
import great_expectations as gx
from sqlalchemy import create_engine, text

engine = create_engine("mysql+pymysql://root:root@mariadb:3306")

def lire(sql, eng=engine, **params):
    return pd.read_sql(text(sql), eng, params=params)

# PARAMÈTRES : couche et lot testés. Pour silver, on changera seulement BASE.
BATCH = "L-2026-10-01"
BASE  = "bronze"

Cellule 2 : Le projet Great Expectations

In [3]:
DOSSIER_GE = "/home/jovyan/work/reports/ge" if os.path.isdir("/home/jovyan/work") else "reports/ge"
os.makedirs(DOSSIER_GE, exist_ok=True)

context    = gx.get_context(project_root_dir=DOSSIER_GE)
datasource = context.sources.add_or_update_pandas(name="assurconnect")
print("GE", gx.__version__, "| projet :", DOSSIER_GE)

GE 0.18.19 | projet : /home/jovyan/work/reports/ge

Cellule 3 : Le catalogue des règles

In [4]:
REGLES = lire("SELECT rule_id, libelle, dimension, severite, seuil_min FROM dq.regle").set_index("rule_id")
print(len(REGLES), "règles dans dq.regle")
display(REGLES)

def mostly(rule_id):
    """Seuil GE (entre 0 et 1) = seuil_min de la règle (en %)."""
    return float(REGLES.loc[rule_id, "seuil_min"]) / 100

CODES_PAYS = sorted(lire("SELECT code_pays FROM silver.ref_pays").code_pays)
print(len(CODES_PAYS), "codes pays de référence")

25 règles dans dq.regle

,libelle,dimension,severite,seuil_min
rule_id,,,,
RQ-001,La date de fin d'un contrat est postérieure à ...,Cohérence,BLOQUANTE,100.0
RQ-002,Un souscripteur personne physique a 18 ans ou ...,Validité métier,BLOQUANTE,100.0
RQ-003,Le téléphone d'un souscripteur est renseigné (...,Complétude,AVERTISSEMENT,98.0
RQ-004,"Pour une adresse en France, le téléphone respe...",Validité format,AVERTISSEMENT,98.0
RQ-005,"Pour une adresse en France, le code postal com...",Validité format,AVERTISSEMENT,98.0
RQ-006,"Pour une adresse en France, le couple code pos...",Exactitude,AVERTISSEMENT,98.0
RQ-007,Le pays (code ISO à deux lettres) appartient à...,Intégrité référentielle,BLOQUANTE,100.0
RQ-008,L'adresse e-mail respecte un motif valide,Validité format,AVERTISSEMENT,98.0
RQ-009,"Le type de personne vaut prospect, souscripteu...",Validité domaine,BLOQUANTE,100.0
RQ-010,"La durée de garantie vaut 12, 24, 36 ou 60 mois",Validité domaine,BLOQUANTE,100.0
RQ-011,Le type de contrat existe dans type_contrat,Intégrité référentielle,BLOQUANTE,100.0
RQ-012,Le souscripteur d'un contrat existe dans le cl...,Intégrité référentielle,BLOQUANTE,100.0
RQ-013,L'assuré d'un contrat existe dans le client ; ...,Intégrité référentielle,BLOQUANTE,100.0
RQ-014,"Adresse de sinistre : format valide, rapproché...","Précision, cohérence",BLOQUANTE,100.0
RQ-015,Un prospect n'a aucun contrat,Cohérence de statut,BLOQUANTE,100.0
RQ-016,Un souscripteur a au moins un contrat,Cohérence de statut,AVERTISSEMENT,98.0
RQ-017,La date de survenance d'un sinistre est compri...,Cohérence inter-tables,BLOQUANTE,100.0
RQ-018,Client actif : contrat en cours ET cotisation ...,Cohérence de définition,BLOQUANTE,100.0
RQ-019,Une personne n'a qu'un seul identifiant client...,Unicité,BLOQUANTE,100.0
RQ-020,Les clés primaires sont uniques et jamais nulles,Unicité,BLOQUANTE,100.0
RQ-021,Réconciliation source vers bronze : mêmes comp...,"Complétude, intégrité",BLOQUANTE,100.0
RQ-022,"Chaque ligne bronze porte lot, source, horodat...",Traçabilité,BLOQUANTE,100.0
RQ-023,Chaque ligne silver et gold référence sa ligne...,Traçabilité,BLOQUANTE,100.0
RQ-024,Conservation : lignes silver + lignes rejetées...,Complétude,BLOQUANTE,100.0
RQ-025,Réconciliation gold vers CRM : même comptage e...,Intégrité,BLOQUANTE,100.0

250 codes pays de référence

Cellule 4 : Charger et préparer les tables

In [5]:
# Dictionnaire de l'US-04 : on renomme les colonnes anonymes du CIF
NOMS_CIF = {"column0": "id_cif", "column1": "nom_ou_raison_sociale", "column2": "prenom",
            "column3": "date_naissance", "column4": "adresse", "column5": "cp", "column6": "ville",
            "column7": "pays", "column8": "telephone", "column9": "email"}

# Table → (nature, clé primaire)
CIBLES = {"crm_client":   ("client",   "client_id"),
          "crm_contrat":  ("contrat",  "contrat_id"),
          "crm_sinistre": ("sinistre", "sinistre_id"),
          "cif_clients":  ("cif",      "id_cif")}

def charger(table, nature, cle):
    df = lire(f"SELECT * FROM {BASE}.{table} WHERE _batch_id = :b", b=BATCH)
    if nature == "cif":
        df = df.rename(columns=NOMS_CIF)
    df["source_systeme"] = df["_source_system"]
    df["cle"] = df[cle]

    if nature == "contrat":
        for c in ["date_debut", "date_fin"]:
            df[c] = pd.to_datetime(df[c], errors="coerce")
        df["duree_garantie_mois"] = pd.to_numeric(df["duree_garantie_mois"], errors="coerce")
        # âge du souscripteur à la date de DÉBUT du contrat (RQ-002)
        naiss = lire(f"SELECT client_id, date_naissance FROM {BASE}.crm_client WHERE _batch_id = :b", b=BATCH)
        df = df.merge(naiss, left_on="souscripteur_id", right_on="client_id", how="left")
        dn, dd = pd.to_datetime(df["date_naissance"], errors="coerce"), df["date_debut"]
        pas_encore_anniv = (dd.dt.month < dn.dt.month) | ((dd.dt.month == dn.dt.month) & (dd.dt.day < dn.dt.day))
        df["age_debut"] = dd.dt.year - dn.dt.year - pas_encore_anniv.astype("Int64")
    return df

DONNEES = {t: (nature, charger(t, nature, cle)) for t, (nature, cle) in CIBLES.items()}
for t, (nature, d) in DONNEES.items():
    print(f"{t:<13} ({nature:<8}) : {len(d):>7} lignes")

crm_client    (client  ) :  100000 lignes
crm_contrat   (contrat ) :  100000 lignes
crm_sinistre  (sinistre) :  100000 lignes
cif_clients   (cif     ) :   40000 lignes

Cellule 5 : La fonction qui exécute une suite

In [9]:
def valider(table, df, ajouter_regles):
    nom_suite = f"{table}_suite"
    try:
        asset = datasource.get_asset(table)
    except Exception:
        asset = datasource.add_dataframe_asset(name=table)
    batch = asset.build_batch_request(dataframe=df)

    context.add_or_update_expectation_suite(expectation_suite_name=nom_suite)
    v = context.get_validator(batch_request=batch, expectation_suite_name=nom_suite)
    ajouter_regles(v)
    v.save_expectation_suite(discard_failed_expectations=False)   # → gx/expectations/<table>_suite.json
    return v.validate().results

Cellule 6 : Les règles, chacune avec son rule_id

In [10]:
SOUSCRIPTEUR_CRM = dict(row_condition='source_systeme == "crm" and type_personne == "souscripteur"', condition_parser="pandas")
FRANCE           = dict(row_condition='pays == "FR"', condition_parser="pandas")

def regles_client(v):
    # RQ-003 : téléphone du souscripteur ni nul, ni vide, ni blanc
    v.expect_column_values_to_not_be_null(column="telephone", mostly=mostly("RQ-003"), meta={"rule_id": "RQ-003"}, **SOUSCRIPTEUR_CRM)
    v.expect_column_values_to_match_regex(column="telephone", regex=r"\S", mostly=mostly("RQ-003"), meta={"rule_id": "RQ-003"}, **SOUSCRIPTEUR_CRM)
    # RQ-009 : type de personne parmi les 3 valeurs autorisées
    v.expect_column_values_to_be_in_set(column="type_personne", value_set=["prospect", "souscripteur", "assure"],
                                        meta={"rule_id": "RQ-009", "nuls_en_echec": True})

def regles_adresse(v):
    # RQ-005 : code postal à 5 chiffres, adresses en France seulement (CRM et CIF)
    v.expect_column_values_to_match_regex(column="cp", regex=r"^\d{5}$", mostly=mostly("RQ-005"),
                                          meta={"rule_id": "RQ-005", "nuls_en_echec": True}, **FRANCE)
    # RQ-007 (bonus) : pays dans la liste de référence
    v.expect_column_values_to_be_in_set(column="pays", value_set=CODES_PAYS, meta={"rule_id": "RQ-007", "nuls_en_echec": True})

def regles_contrat(v):
    # RQ-001 : date de fin strictement après la date de début
    v.expect_column_pair_values_A_to_be_greater_than_B(column_A="date_fin", column_B="date_debut", or_equal=False, meta={"rule_id": "RQ-001"})
    # RQ-002 : souscripteur de 18 ans ou plus à la date de début
    v.expect_column_values_to_be_between(column="age_debut", min_value=18, meta={"rule_id": "RQ-002"})
    # RQ-010 : durée de garantie parmi 12, 24, 36, 60
    v.expect_column_values_to_be_in_set(column="duree_garantie_mois", value_set=[12, 24, 36, 60],
                                        meta={"rule_id": "RQ-010", "nuls_en_echec": True})

def cle_primaire(v):
    # RQ-020 : clé primaire jamais nulle et unique
    v.expect_column_values_to_not_be_null(column="cle", meta={"rule_id": "RQ-020"})
    v.expect_column_values_to_be_unique(column="cle", meta={"rule_id": "RQ-020"})

SUITES = {"client":   [regles_client, regles_adresse, cle_primaire],
          "contrat":  [regles_contrat, cle_primaire],
          "sinistre": [cle_primaire],
          "cif":      [regles_adresse, cle_primaire]}

Cellule 7 : Exécuter et calculer le taux par règle

In [8]:
mesures = []
for table, (nature, df) in DONNEES.items():
    resultats = valider(table, df, lambda v: [f(v) for f in SUITES[nature]])
    par_regle = {}
    for r in resultats:
        meta = r.expectation_config.meta
        n  = r.result["element_count"]
        ko = r.result["unexpected_count"] + (r.result.get("missing_count", 0) if meta.get("nuls_en_echec") else 0)
        t0, k0 = par_regle.get(meta["rule_id"], (n, 0))
        par_regle[meta["rule_id"]] = (t0, k0 + ko)
    for rule, (n, ko) in par_regle.items():
        mesures.append({"rule_id": rule, "table": table, "testees": int(n), "echecs": int(ko)})

bilan = pd.DataFrame(mesures).sort_values(["rule_id", "table"]).reset_index(drop=True)
bilan["conformite_pct"] = (100 * (bilan.testees - bilan.echecs) / bilan.testees).round(3)
bilan["seuil_pct"] = [float(REGLES.loc[r, "seuil_min"]) for r in bilan.rule_id]
bilan["severite"]  = [REGLES.loc[r, "severite"] for r in bilan.rule_id]
bilan["verdict"]   = ["conforme" if c >= s else "sous le seuil" for c, s in zip(bilan.conformite_pct, bilan.seuil_pct)]
bilan

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/36 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/7 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/23 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/9 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/22 [00:00<?, ?it/s]

,rule_id,table,testees,echecs,conformite_pct,seuil_pct,severite,verdict
0,RQ-001,crm_contrat,100000,800,99.200,100.0,BLOQUANTE,sous le seuil
1,RQ-002,crm_contrat,100000,301,99.699,100.0,BLOQUANTE,sous le seuil
2,RQ-003,crm_client,49898,5989,87.998,98.0,AVERTISSEMENT,sous le seuil
3,RQ-005,cif_clients,39401,0,100.000,98.0,AVERTISSEMENT,conforme
4,RQ-005,crm_client,95437,1456,98.474,98.0,AVERTISSEMENT,conforme
5,RQ-007,cif_clients,40000,0,100.000,100.0,BLOQUANTE,conforme
6,RQ-007,crm_client,100000,3050,96.950,100.0,BLOQUANTE,sous le seuil
7,RQ-009,crm_client,100000,200,99.800,100.0,BLOQUANTE,sous le seuil
8,RQ-010,crm_contrat,100000,600,99.400,100.0,BLOQUANTE,sous le seuil
9,RQ-020,cif_clients,40000,0,100.000,100.0,BLOQUANTE,conforme
10,RQ-020,crm_client,100000,0,100.000,100.0,BLOQUANTE,conforme
11,RQ-020,crm_contrat,100000,0,100.000,100.0,BLOQUANTE,conforme
12,RQ-020,crm_sinistre,100000,0,100.000,100.0,BLOQUANTE,conforme

In [16]:
TYPES = {
    "RQ-001": "column_pair_values_A_to_be_greater_than_B (date_fin > date_debut)",
    "RQ-002": "column_values_to_be_between (age_debut ≥ 18)",
    "RQ-003": "column_values_to_not_be_null + match_regex \\S (souscripteurs)",
    "RQ-005": "column_values_to_match_regex ^\\d{5}$ (adresses FR)",
    "RQ-007": "column_values_to_be_in_set (silver.ref_pays)",
    "RQ-009": "column_values_to_be_in_set (prospect, souscripteur, assure)",
    "RQ-010": "column_values_to_be_in_set (12, 24, 36, 60)",
    "RQ-020": "column_values_to_not_be_null + to_be_unique (clé)",
}
page15 = bilan.assign(expectation=bilan.rule_id.map(TYPES))[
    ["rule_id", "table", "expectation", "testees", "echecs", "conformite_pct", "severite"]]
page15.columns = ["Règle", "Table bronze", "Expectation (type)", "Testées", "En échec", "Taux (%)", "Sévérité"]
pd.set_option("display.max_colwidth", None)
page15

,Règle,Table bronze,Expectation (type),Testées,En échec,Taux (%),Sévérité
0,RQ-001,crm_contrat,column_pair_values_A_to_be_greater_than_B (date_fin > date_debut),100000,800,99.200,BLOQUANTE
1,RQ-002,crm_contrat,column_values_to_be_between (age_debut ≥ 18),100000,301,99.699,BLOQUANTE
2,RQ-003,crm_client,column_values_to_not_be_null + match_regex \S (souscripteurs),49898,5989,87.998,AVERTISSEMENT
3,RQ-005,cif_clients,column_values_to_match_regex ^\d{5}$ (adresses FR),39401,0,100.000,AVERTISSEMENT
4,RQ-005,crm_client,column_values_to_match_regex ^\d{5}$ (adresses FR),95437,1456,98.474,AVERTISSEMENT
5,RQ-007,cif_clients,column_values_to_be_in_set (silver.ref_pays),40000,0,100.000,BLOQUANTE
6,RQ-007,crm_client,column_values_to_be_in_set (silver.ref_pays),100000,3050,96.950,BLOQUANTE
7,RQ-009,crm_client,"column_values_to_be_in_set (prospect, souscripteur, assure)",100000,200,99.800,BLOQUANTE
8,RQ-010,crm_contrat,"column_values_to_be_in_set (12, 24, 36, 60)",100000,600,99.400,BLOQUANTE
9,RQ-020,cif_clients,column_values_to_not_be_null + to_be_unique (clé),40000,0,100.000,BLOQUANTE
10,RQ-020,crm_client,column_values_to_not_be_null + to_be_unique (clé),100000,0,100.000,BLOQUANTE
11,RQ-020,crm_contrat,column_values_to_not_be_null + to_be_unique (clé),100000,0,100.000,BLOQUANTE
12,RQ-020,crm_sinistre,column_values_to_not_be_null + to_be_unique (clé),100000,0,100.000,BLOQUANTE

Cellule 9 : Les pièges, avant / après

In [11]:
cl  = DONNEES["crm_client"][1]
cif = DONNEES["cif_clients"][1]
sous = cl[(cl.source_systeme == "crm") & (cl.type_personne == "souscripteur")]

# Piège 1 — RQ-003 : nul, vide et blanc sont trois cas différents
avant_rq003 = int(sous.telephone.isna().sum())
apres_rq003 = int((sous.telephone.isna() | (sous.telephone.fillna("x").str.strip() == "")).sum())

# Piège 2 — RQ-005 : sans filtre « France », les CP étrangers comptent comme erreurs
avant_crm = int((~cl.cp.fillna("").str.fullmatch(r"\d{5}")).sum())
apres_crm = int((~cl[cl.pays == "FR"].cp.fillna("").str.fullmatch(r"\d{5}")).sum())
avant_cif = int((~cif.cp.fillna("").str.fullmatch(r"\d{5}")).sum())
apres_cif = int((~cif[cif.pays == "FR"].cp.fillna("").str.fullmatch(r"\d{5}")).sum())

# Piège 3 — RQ-009 : la comparaison est exacte (casse comprise)
domaine = ["prospect", "souscripteur", "assure"]
avant_rq009 = int((~cl.type_personne.str.lower().isin(domaine)).sum())   # insensible à la casse
apres_rq009 = int((~cl.type_personne.isin(domaine)).sum())               # exacte

pieges = pd.DataFrame([
    ["RQ-003", "nul, vide et blanc : tester seulement NULL",    avant_rq003, apres_rq003],
    ["RQ-005", "adresses étrangères (CRM) : filtre pays = FR",  avant_crm,   apres_crm],
    ["RQ-005", "adresses étrangères (CIF) : filtre pays = FR",  avant_cif,   apres_cif],
    ["RQ-009", "comparaison exacte (casse) vs insensible",      avant_rq009, apres_rq009],
], columns=["Règle", "Piège", "Avant correction", "Après correction"])
pieges

,Règle,Piège,Avant correction,Après correction
0,RQ-003,"nul, vide et blanc : tester seulement NULL",1995,5989
1,RQ-005,adresses étrangères (CRM) : filtre pays = FR,2317,1456
2,RQ-005,adresses étrangères (CIF) : filtre pays = FR,341,0
3,RQ-009,comparaison exacte (casse) vs insensible,120,200

# **US-11**

In [18]:
# US-11 · Lignes en échec : export (identifiant + motif) et échantillon commenté de 20 lignes
import numpy as np

contrats = DONNEES["crm_contrat"][1]
clients  = DONNEES["crm_client"][1]
echecs = []

def ajouter(rule_id, table, df, masque, valeur, famille, action):
    """Garde l'identifiant, la valeur en échec, la famille d'erreur et l'action proposée."""
    m = pd.Series(masque, index=df.index).fillna(False).astype(bool)
    if not m.any():
        return
    echecs.append(pd.DataFrame({
        "rule_id": rule_id, "table_source": table,
        "cle": df.loc[m, "cle"], "bronze_row_id": df.loc[m, "bronze_row_id"],
        "valeur_en_echec": pd.Series(valeur, index=df.index)[m].astype(str),
        "famille": pd.Series(famille, index=df.index)[m],
        "action_proposee": action,
    }))

# RQ-001 — fin = début ou fin avant début
d, f = contrats.date_debut, contrats.date_fin
ajouter("RQ-001", "crm_contrat", contrats, d.notna() & f.notna() & (f <= d),
        d.dt.date.astype(str) + " → " + f.dt.date.astype(str),
        np.where(f == d, "durée nulle (fin = début)", "dates inversées (fin < début)"),
        "Équipe contrats : corriger les dates à la source ; Data Steward : contrôle à la saisie")

# RQ-002 — souscripteur mineur à la date de début
age = pd.to_numeric(contrats.age_debut, errors="coerce")
ajouter("RQ-002", "crm_contrat", contrats, age.notna() & (age < 18),
        age.astype("Int64").astype(str) + " ans",
        "souscripteur de " + age.astype("Int64").astype(str) + " ans",
        "Data Owner : décider si un mineur peut souscrire (ex. jeune conducteur avec garant)")

# RQ-003 — téléphone du souscripteur nul, vide ou blanc
sous = (clients.source_systeme == "crm") & (clients.type_personne == "souscripteur")
tel = clients.telephone
ajouter("RQ-003", "crm_client", clients, sous & (tel.isna() | (tel.fillna("x").str.strip() == "")),
        tel.map(repr),
        np.where(tel.isna(), "NULL", np.where(tel.fillna("") == "", "chaîne vide", "espaces seuls")),
        "Équipe CRM : rendre le téléphone obligatoire pour un souscripteur ; recontacter le client")

# RQ-005 — CP d'une adresse française qui n'a pas 5 chiffres (CRM et CIF)
for table in ["crm_client", "cif_clients"]:
    df = DONNEES[table][1]
    fr = df.pays == "FR"
    cp = df.cp.fillna("")
    ajouter("RQ-005", table, df, fr & ~cp.str.fullmatch(r"\d{5}"),
            cp + " " + df.ville.fillna(""),
            np.where(cp.str.fullmatch(r"\d{4}"), "zéro initial perdu (A01)", "autre format"),
            "Data Steward : restaurer le zéro en silver ; équipe CRM : stocker le CP en texte")

# RQ-009 — type de personne hors domaine (comparaison exacte)
tp = clients.type_personne
fam = np.select([tp.str.lower().isin(["prospect", "souscripteur", "assure"]),
                 tp.isin(["assuré"]), tp.str.endswith(".", na=False)],
                ["casse", "accent", "abréviation"], default="hors domaine")
ajouter("RQ-009", "crm_client", clients, ~tp.isin(["prospect", "souscripteur", "assure"]),
        tp, fam, "Data Steward : table de correspondance en silver ; Data Owner : statut de « client »")

# RQ-010 — durée hors catalogue
du = pd.to_numeric(contrats.duree_garantie_mois, errors="coerce")
ajouter("RQ-010", "crm_contrat", contrats, ~du.isin([12, 24, 36, 60]),
        du.astype("Int64").astype(str) + " mois",
        "durée " + du.astype("Int64").astype(str) + " mois hors catalogue",
        "Data Owner : ajouter la durée au catalogue ou la refuser ; équipe contrats : corriger")

export = pd.concat(echecs, ignore_index=True)

# Échantillon de 20 lignes : une par famille d'erreur, puis on complète règle par règle
ech = export.groupby(["rule_id", "famille"]).head(1)
ech = pd.concat([ech, export.drop(ech.index).groupby("rule_id").head(2)]).head(20)
ech = ech.sort_values(["rule_id", "famille"]).reset_index(drop=True)

# Fichiers : export complet (identifiant + motif, sans données personnelles) et échantillon
export.to_csv(f"{DOSSIER_GE}/us11_lignes_en_echec.csv", index=False, encoding="utf-8-sig")
ech.to_csv(f"{DOSSIER_GE}/us11_echantillon_20_lignes_commentees.csv", index=False, encoding="utf-8-sig")

print("Lignes en échec :", len(export))
display(export.groupby(["rule_id", "table_source"]).size().rename("lignes"))
print(f"\nÉchantillon : {len(ech)} lignes")
pd.set_option("display.max_colwidth", None)
display(ech[["rule_id", "cle", "valeur_en_echec", "famille", "action_proposee"]])

Lignes en échec : 9346

rule_id  table_source
RQ-001   crm_contrat      800
RQ-002   crm_contrat      301
RQ-003   crm_client      5989
RQ-005   crm_client      1456
RQ-009   crm_client       200
RQ-010   crm_contrat      600
Name: lignes, dtype: int64

Échantillon : 20 lignes

,rule_id,cle,valeur_en_echec,famille,action_proposee
0,RQ-001,CT0000147,2014-04-05 → 2014-03-08,dates inversées (fin < début),Équipe contrats : corriger les dates à la source ; Data Steward : contrôle à la saisie
1,RQ-001,CT0000044,2014-02-03 → 2014-02-03,durée nulle (fin = début),Équipe contrats : corriger les dates à la source ; Data Steward : contrôle à la saisie
2,RQ-001,CT0000106,2014-03-11 → 2014-03-11,durée nulle (fin = début),Équipe contrats : corriger les dates à la source ; Data Steward : contrôle à la saisie
3,RQ-001,CT0000158,2014-04-16 → 2014-04-16,durée nulle (fin = début),Équipe contrats : corriger les dates à la source ; Data Steward : contrôle à la saisie
4,RQ-002,CT0002784,16 ans,souscripteur de 16 ans,Data Owner : décider si un mineur peut souscrire (ex. jeune conducteur avec garant)
5,RQ-002,CT0000387,17 ans,souscripteur de 17 ans,Data Owner : décider si un mineur peut souscrire (ex. jeune conducteur avec garant)
6,RQ-002,CT0001356,17 ans,souscripteur de 17 ans,Data Owner : décider si un mineur peut souscrire (ex. jeune conducteur avec garant)
7,RQ-003,A-10115,None,NULL,Équipe CRM : rendre le téléphone obligatoire pour un souscripteur ; recontacter le client
8,RQ-003,A-10011,'',chaîne vide,Équipe CRM : rendre le téléphone obligatoire pour un souscripteur ; recontacter le client
9,RQ-003,A-10012,' ',espaces seuls,Équipe CRM : rendre le téléphone obligatoire pour un souscripteur ; recontacter le client
10,RQ-005,A-10062,1500 Ambérieu-en-Bugey,zéro initial perdu (A01),Data Steward : restaurer le zéro en silver ; équipe CRM : stocker le CP en texte
11,RQ-009,A-10700,prosp.,abréviation,Data Steward : table de correspondance en silver ; Data Owner : statut de « client »
12,RQ-009,A-10751,assuré,accent,Data Steward : table de correspondance en silver ; Data Owner : statut de « client »
13,RQ-009,A-10305,Souscripteur,casse,Data Steward : table de correspondance en silver ; Data Owner : statut de « client »
14,RQ-009,A-10198,client,hors domaine,Data Steward : table de correspondance en silver ; Data Owner : statut de « client »
15,RQ-010,CT0000001,120 mois,durée 120 mois hors catalogue,Data Owner : ajouter la durée au catalogue ou la refuser ; équipe contrats : corriger
16,RQ-010,CT0003259,18 mois,durée 18 mois hors catalogue,Data Owner : ajouter la durée au catalogue ou la refuser ; équipe contrats : corriger
17,RQ-010,CT0000931,48 mois,durée 48 mois hors catalogue,Data Owner : ajouter la durée au catalogue ou la refuser ; équipe contrats : corriger
18,RQ-010,CT0006862,6 mois,durée 6 mois hors catalogue,Data Owner : ajouter la durée au catalogue ou la refuser ; équipe contrats : corriger
19,RQ-010,CT0005435,9 mois,durée 9 mois hors catalogue,Data Owner : ajouter la durée au catalogue ou la refuser ; équipe contrats : corriger