# **US-12**

Cellule 1 : Préparation

In [1]:
import os, re, json, subprocess
import pandas as pd
import yaml
from sqlalchemy import create_engine, text

engine = create_engine("mysql+pymysql://root:root@mariadb:3306")
def lire(sql, eng=engine, **params):
    return pd.read_sql(text(sql), eng, params=params)

BATCH = "L-2026-10-01"
SODA  = "/home/jovyan/work/soda"                     # dossier Soda du dépôt (dans le conteneur Jupyter)
os.makedirs(f"{SODA}/checks/bronze", exist_ok=True)
os.makedirs(f"{SODA}/resultats", exist_ok=True)

# Sévérité de chaque règle (BLOQUANTE ou AVERTISSEMENT), lue dans le catalogue
REGLES = lire("SELECT rule_id, libelle, severite, seuil_min FROM dq.regle").set_index("rule_id")

CODES_RETOUR = {0: "tout passe", 1: "avertissements", 2: "échecs", 3: "erreur d'exécution"}
print(len(REGLES), "règles | dossier Soda :", SODA)

25 règles | dossier Soda : /home/jovyan/work/soda

Cellule 2 : Une source de données par couche

In [2]:
config = yaml.safe_load(open(f"{SODA}/configuration.yml", encoding="utf-8"))
sources = [k.replace("data_source ", "") for k in config]
print("Sources de données déclarées :", sources)
for s in sources:
    print(f"  {s:<7} → base {config['data_source ' + s].get('database')}")

Sources de données déclarées : ['crm', 'bronze', 'silver', 'gold']
  crm     → base crm
  bronze  → base bronze
  silver  → base silver
  gold    → base gold

Cellule 3 : Lire un fichier de checks SodaCL

In [11]:
print(open(f"{SODA}/checks/client_checks.yml", encoding="utf-8").read())

checks for client:
  # RQ-020 : clé primaire unique et renseignée
  - duplicate_count(client_id) = 0:
      name: RQ-020 identifiant client unique
  - missing_count(client_id) = 0:
      name: RQ-020 identifiant client renseigne

  # RQ-009 : type de personne dans le domaine
  - invalid_count(type_personne) = 0:
      name: RQ-009 type de personne autorise
      valid values: ['prospect', 'souscripteur', 'assure']

  # RQ-003 : téléphone d'un souscripteur renseigné (nul, vide ou blanc) — AVERTISSEMENT
  - failed rows:
      name: RQ-003 telephone du souscripteur renseigne
      fail condition: type_personne = 'souscripteur' AND (telephone IS NULL OR TRIM(telephone) = '')
      warn: when > 0

  # RQ-005 : code postal à 5 chiffres pour une adresse en France — AVERTISSEMENT
  - failed rows:
      name: RQ-005 code postal sur 5 chiffres (France)
      fail condition: pays = 'FR' AND cp NOT REGEXP '^[0-9]{5}$'
      warn: when > 0

  # RQ-007 : pays dans la liste de référence
  - failed rows:
      name: RQ-007 pays dans la liste de reference
      fail query: |
        SELECT client_id FROM client WHERE pays NOT IN (SELECT code_pays FROM silver.ref_pays)

  # RQ-015 : un prospect n'a aucun contrat (échoue sur les données brutes)
  - failed rows:
      name: RQ-015 prospect sans contrat
      fail query: |
        SELECT c.client_id FROM client c
        WHERE c.type_personne = 'prospect'
          AND EXISTS (SELECT 1 FROM contrat k WHERE k.souscripteur_id = c.client_id)

Cellule 4 : Créer les fichiers de bronze

In [12]:
# Dans crm les tables s'appellent client, contrat… ; dans bronze : crm_client, crm_contrat…
TABLES_BRONZE = {"client": "crm_client", "contrat": "crm_contrat",
                 "sinistre": "crm_sinistre", "type_contrat": "crm_type_contrat"}

def vers_bronze(texte):
    """Remplace les noms de tables crm par ceux de bronze, sans toucher au reste."""
    for source, cible in TABLES_BRONZE.items():
        texte = re.sub(rf"(checks for |filter |FROM |JOIN |exist in )({source})\b", rf"\1{cible}", texte)
    # bronze garde tout en texte : la durée 12 devient '12'
    return texte.replace("[12, 24, 36, 60]", "['12', '24', '36', '60']")

for nom in ["client", "contrat", "sinistre"]:
    texte = open(f"{SODA}/checks/{nom}_checks.yml", encoding="utf-8").read()
    open(f"{SODA}/checks/bronze/{nom}_checks.yml", "w", encoding="utf-8").write(vers_bronze(texte))
    print("créé :", f"soda/checks/bronze/{nom}_checks.yml")

créé : soda/checks/bronze/client_checks.yml
créé : soda/checks/bronze/contrat_checks.yml
créé : soda/checks/bronze/sinistre_checks.yml

Cellule 5 : Les contrôles d’intégrité ajoutés pour bronze

In [13]:
open(f"{SODA}/checks/bronze/integrite_checks.yml", "w", encoding="utf-8").write("""# RQ-016 : un souscripteur a au moins un contrat (AVERTISSEMENT dans dq.regle)
checks for crm_client:
  - failed rows:
      name: RQ-016 souscripteur sans contrat
      fail query: |
        SELECT k.client_id FROM crm_client k
        WHERE k.type_personne = 'souscripteur'
          AND NOT EXISTS (SELECT 1 FROM crm_contrat c WHERE c.souscripteur_id = k.client_id)
      warn: when > 0

# Relation sinistre → contrat : aucune clé étrangère n'est déclarée dans la base
checks for crm_sinistre:
  - values in (contrat_id) must exist in crm_contrat (contrat_id):
      name: Relation sinistre vers contrat
""")
print("créé : soda/checks/bronze/integrite_checks.yml")

créé : soda/checks/bronze/integrite_checks.yml

Cellule 6 : Lancer soda scan en ligne de commande

In [14]:
def scan(source, fichier):
    """Lance `soda scan` (ligne de commande) et renvoie (code retour, liste des contrôles)."""
    nom = os.path.basename(fichier).replace(".yml", "")
    resultat_json = f"{SODA}/resultats/{source}_{nom}.json"
    p = subprocess.run(["soda", "scan", "-d", source, "-c", f"{SODA}/configuration.yml",
                        fichier, "-srf", resultat_json],
                       capture_output=True, text=True)
    if not os.path.exists(resultat_json):          # erreur grave : on affiche le journal
        print(p.stdout[-2000:], p.stderr[-2000:])
        return p.returncode, []
    r = json.load(open(resultat_json, encoding="utf-8"))
    valeurs = {m["identity"]: m["value"] for m in r.get("metrics", [])}
    controles = []
    for c in r["checks"]:
        m = re.search(r"RQ-\d{3}", c["name"])
        controles.append({"fichier": nom, "rule_id": m.group(0) if m else None,
                          "controle": c["name"], "resultat": c["outcome"],
                          "valeur": [valeurs.get(x) for x in c.get("metrics", [])]})
    return p.returncode, controles

Cellule 7 : Scanner bronze, fichier par fichier

In [15]:
CONTROLES, CODES = [], {}
for nom in ["client_checks", "contrat_checks", "sinistre_checks", "integrite_checks"]:
    CODES[nom], c = scan("bronze", f"{SODA}/checks/bronze/{nom}.yml")
    CONTROLES += c

CTRL = pd.DataFrame(CONTROLES, dtype=object)
CTRL["severite"] = CTRL.rule_id.map(REGLES.severite)       # BLOQUANTE ou AVERTISSEMENT
pd.set_option("display.max_colwidth", None)
display(CTRL[["fichier", "rule_id", "controle", "resultat", "valeur", "severite"]]
        .sort_values(["fichier", "rule_id"]))

print("Codes retour par fichier :", {k: f"{v} ({CODES_RETOUR.get(v, '?')})" for k, v in CODES.items()})

,fichier,rule_id,controle,resultat,valeur,severite
0,client_checks,RQ-003,RQ-003 telephone du souscripteur renseigne,warn,[5989],AVERTISSEMENT
1,client_checks,RQ-005,RQ-005 code postal sur 5 chiffres (France),warn,[1456],AVERTISSEMENT
2,client_checks,RQ-007,RQ-007 pays dans la liste de reference,fail,[3050],BLOQUANTE
6,client_checks,RQ-009,RQ-009 type de personne autorise,fail,[200],BLOQUANTE
3,client_checks,RQ-015,RQ-015 prospect sans contrat,fail,[479],BLOQUANTE
4,client_checks,RQ-020,RQ-020 identifiant client unique,pass,[0],BLOQUANTE
5,client_checks,RQ-020,RQ-020 identifiant client renseigne,pass,[0],BLOQUANTE
7,contrat_checks,RQ-001,RQ-001 date de fin posterieure a la date de debut,fail,[800],BLOQUANTE
13,contrat_checks,RQ-010,RQ-010 duree de garantie autorisee,fail,[600],BLOQUANTE
8,contrat_checks,RQ-011,RQ-011 type de contrat connu,fail,[200],BLOQUANTE
9,contrat_checks,RQ-012,RQ-012 souscripteur existant,fail,[1000],BLOQUANTE
14,contrat_checks,RQ-013,RQ-013 assure existant (sentinelle 0 exclue),fail,[300],BLOQUANTE
10,contrat_checks,RQ-018,RQ-018 ecart client actif commercial vs CD-001,fail,[11878.0],BLOQUANTE
11,contrat_checks,RQ-020,RQ-020 identifiant de contrat unique,pass,[0],BLOQUANTE
12,contrat_checks,RQ-020,RQ-020 identifiant de contrat renseigne,pass,[0],BLOQUANTE
20,integrite_checks,RQ-016,RQ-016 souscripteur sans contrat,warn,[955],AVERTISSEMENT
21,integrite_checks,None,Relation sinistre vers contrat,pass,[0],NaN
16,sinistre_checks,RQ-014,RQ-014 taux d'adresses de sinistre non reconnues (BAN),fail,[12.1],BLOQUANTE
18,sinistre_checks,RQ-014,RQ-014 code postal de sinistre sur 5 chiffres,pass,[0],BLOQUANTE
19,sinistre_checks,RQ-014,RQ-014 adresse de sinistre renseignee,pass,[0],BLOQUANTE
15,sinistre_checks,RQ-017,RQ-017 sinistre hors periode de garantie,fail,[1200],BLOQUANTE
17,sinistre_checks,RQ-020,RQ-020 identifiant de sinistre unique,pass,[0],BLOQUANTE

Codes retour par fichier : {'client_checks': '2 (échecs)', 'contrat_checks': '2 (échecs)', 'sinistre_checks': '2 (échecs)', 'integrite_checks': '1 (avertissements)'}

Cellule 8 — La décision de la porte

In [16]:
# %% US-12 · Décision de la porte : seuls les échecs de règles BLOQUANTES la ferment
bloquants      = sorted(CTRL[(CTRL.resultat == "fail") & (CTRL.severite == "BLOQUANTE")].rule_id.dropna().unique())
avertissements = CTRL[CTRL.resultat == "warn"].controle.tolist()
incoherents    = CTRL[(CTRL.severite == "AVERTISSEMENT") & (CTRL.resultat == "fail")].controle.tolist()

code_porte = 2 if bloquants else (1 if avertissements else 0)
print("Règles bloquantes en échec :", bloquants or "aucune")
print("Avertissements (n'arrêtent pas le pipeline) :", avertissements or "aucun")
print("Règles AVERTISSEMENT écrites en échec (à passer en warn:) :", incoherents or "aucune ✅")
print(f"\nCode retour de la porte : {code_porte} ({CODES_RETOUR[code_porte]})")
# Dans un pipeline, l'étape se termine par : sys.exit(code_porte)

Règles bloquantes en échec : ['RQ-001', 'RQ-007', 'RQ-009', 'RQ-010', 'RQ-011', 'RQ-012', 'RQ-013', 'RQ-014', 'RQ-015', 'RQ-017', 'RQ-018']
Avertissements (n'arrêtent pas le pipeline) : ['RQ-003 telephone du souscripteur renseigne', 'RQ-005 code postal sur 5 chiffres (France)', 'RQ-016 souscripteur sans contrat']
Règles AVERTISSEMENT écrites en échec (à passer en warn:) : aucune ✅

Code retour de la porte : 2 (échecs)

# **US-16**

Cellule 1 : Le tableau des orphelins par relation

In [18]:
def valeur(rule_id=None, controle=None):
    """Nombre d'orphelins mesuré par Soda (cellule 7 de l'US-12)."""
    ligne = CTRL[CTRL.rule_id == rule_id] if rule_id else CTRL[CTRL.controle == controle]
    v = ligne.valeur.iloc[0]
    return int(v[0] if isinstance(v, list) else v)       # Soda renvoie une liste : [3050] → 3050

def total(requete):
    return int(lire(requete, b=BATCH).iloc[0, 0])

RELATIONS = pd.DataFrame([
    ("RQ-007 · client.pays → ref_pays",
     total("SELECT COUNT(*) FROM bronze.crm_client WHERE _batch_id = :b"), valeur("RQ-007")),
    ("RQ-011 · contrat.code_type → type_contrat",
     total("SELECT COUNT(*) FROM bronze.crm_contrat WHERE _batch_id = :b"), valeur("RQ-011")),
    ("RQ-012 · contrat.souscripteur_id → client",
     total("SELECT COUNT(*) FROM bronze.crm_contrat WHERE _batch_id = :b"), valeur("RQ-012")),
    ("RQ-013 · contrat.assure_id → client (sentinelle 0 exclue)",
     total("SELECT COUNT(*) FROM bronze.crm_contrat WHERE _batch_id = :b AND assure_id <> '0'"), valeur("RQ-013")),
    ("sinistre.contrat_id → contrat",
     total("SELECT COUNT(*) FROM bronze.crm_sinistre WHERE _batch_id = :b"), valeur(controle="Relation sinistre vers contrat")),
], columns=["relation", "lignes_testees", "orphelins"])
RELATIONS["pct"] = (100 * RELATIONS.orphelins / RELATIONS.lignes_testees).round(3)
RELATIONS

,relation,lignes_testees,orphelins,pct
0,RQ-007 · client.pays → ref_pays,100000,3050,3.05
1,RQ-011 · contrat.code_type → type_contrat,100000,200,0.20
2,RQ-012 · contrat.souscripteur_id → client,100000,1000,1.00
3,RQ-013 · contrat.assure_id → client (sentinelle 0 exclue),60000,300,0.50
4,sinistre.contrat_id → contrat,100000,0,0.00

Cellule 2 : Regarder les orphelins

In [19]:
# %% US-16 · Les orphelins eux-mêmes : quelles valeurs, d'où viennent-ils ?
# RQ-011 : quels codes de type de contrat sont inconnus ?
display(lire("""SELECT c.code_type, COUNT(*) AS contrats
                FROM bronze.crm_contrat c
                LEFT JOIN bronze.crm_type_contrat t ON t.code_type = c.code_type AND t._batch_id = :b
                WHERE c._batch_id = :b AND t.code_type IS NULL
                GROUP BY c.code_type""", b=BATCH))

# RQ-012 / RQ-013 : les identifiants orphelins ressemblent-ils aux identifiants existants ?
display(lire("""SELECT 'existants' AS groupe, MIN(CAST(SUBSTRING(client_id, 3) AS UNSIGNED)) AS num_min,
                       MAX(CAST(SUBSTRING(client_id, 3) AS UNSIGNED)) AS num_max
                FROM bronze.crm_client WHERE _batch_id = :b
                UNION ALL
                SELECT 'souscripteurs orphelins', MIN(CAST(SUBSTRING(c.souscripteur_id, 3) AS UNSIGNED)),
                       MAX(CAST(SUBSTRING(c.souscripteur_id, 3) AS UNSIGNED))
                FROM bronze.crm_contrat c
                LEFT JOIN bronze.crm_client k ON k.client_id = c.souscripteur_id AND k._batch_id = :b
                WHERE c._batch_id = :b AND k.client_id IS NULL""", b=BATCH))

# Exemples de contrats dont le souscripteur est introuvable
display(lire("""SELECT c.contrat_id, c.souscripteur_id, c.date_debut
                FROM bronze.crm_contrat c
                LEFT JOIN bronze.crm_client k ON k.client_id = c.souscripteur_id AND k._batch_id = :b
                WHERE c._batch_id = :b AND k.client_id IS NULL LIMIT 5""", b=BATCH))

  code_type  contrats
0       A01        50
1       T13        50
2       T99        50
3       TXX        50

                    groupe  num_min  num_max
0                existants     1000    40977
1  souscripteurs orphelins    90001    99980

  contrat_id souscripteur_id  date_debut
0  CT0000031         H-97935  2014-01-23
1  CT0000046         S-97321  2014-02-03
2  CT0000071         S-95441  2014-02-17
3  CT0000072         S-97658  2014-02-17
4  CT0000188         A-95721  2014-05-03

Cellule 3 : L’effet de la sentinelle sur RQ-013

In [20]:
# %% US-16 · RQ-013 avec et sans traitement de la sentinelle 0
brut = total("""SELECT COUNT(*) FROM bronze.crm_contrat c
                LEFT JOIN bronze.crm_client k ON k.client_id = c.assure_id AND k._batch_id = :b
                WHERE c._batch_id = :b AND k.client_id IS NULL""")
print(f"RQ-013 sans traitement de la sentinelle : {brut} orphelins sur 100 000")
print(f"RQ-013 sentinelle 0 exclue             : {valeur('RQ-013')} orphelins sur 60 000")

RQ-013 sans traitement de la sentinelle : 40300 orphelins sur 100 000
RQ-013 sentinelle 0 exclue             : 300 orphelins sur 60 000